package gocolournamer

import (
	"fmt"
	"math"
	"regexp"
	"strconv"
	"strings"
)

type (
	//Named struct contains nearest specific colour name, general hue name, and hue's hexcode
	Named struct {
		Hex    string `json:"hex"`
		Colour string `json:"colour"`
		Hue    string `json:"hue"`
		Huehex string `json:"huehex"`
	}

	//colour stores all information about one colour
	colour struct {
		hex    string
		colour string
		hue    string
		r      int64
		g      int64
		b      int64
		h      float64
		s      float64
		l      float64
	}

	//hueShade stores a hue and it's hex
	hueShade struct {
		hex  string
		name string
	}
)

//Hex number with optional leading hash regex string
const hexrxp = `(^#{0,1}[0-9A-F]{6}$)|(^#{0,1}[0-9A-F]{3}$)`

func init() {
	populate()
}

//populate calculates RGB and HSL values for each colour in colour slice
func populate() {
	for k, v := range colours {
		colours[k].r, colours[k].g, colours[k].b = rgb(v.hex)
		colours[k].h, colours[k].s, colours[k].l = hsl(colours[k].r, colours[k].g, colours[k].b)
	}
}

//ToNearestColour takes a hex string and returns a named object
//hex string may have an optional leading hash, followed by 3 or 6 characters in range [0-9, A-F]
//Named object contains the closet matched colour (calculated from RGB and HSL distances)
func ToNearestColour(hex string) (names Named, err error) {
	hex, err = validHex(hex)
	if err != nil {
		return
	}
	names.Hex = hex
	r, g, b := rgb(hex)
	h, s, l := hsl(r, g, b)

	var ndf, ndf1, ndf2 float64
	var df float64 = -1

	//check each colour for exact or closest match
	for _, v := range colours {
		if hex == v.hex {
			names.Colour = v.colour
			names.Hue = v.hue
			names.Huehex = shade(names.Hue)
			return
		}

		//root-mean-square deviation from RGB
		ndf1 = math.Pow(float64(r-v.r), 2) + math.Pow(float64(g-v.g), 2) + math.Pow(float64(b-v.b), 2)
		//root-mean-square deviation from HSL
		ndf2 = math.Pow(h-v.h, 2) + math.Pow(s-v.s, 2) + math.Pow(l-v.l, 2)
		ndf = ndf1 + ndf2*2

		//if coloser to this colour than any previous colour
		if df < 0 || df > ndf {
			df = ndf
			names.Colour = v.colour
			names.Hue = v.hue
			names.Huehex = shade(names.Hue)
		}
	}
	return
}

//validHex validates and correctly formats a hex colour
func validHex(hex string) (h string, err error) {
	reg := regexp.MustCompile(hexrxp)
	if !reg.MatchString(hex) {
		err = ErrInvalidHex
		return
	}
	if hex[0] == '#' {
		hex = hex[1:]
	}
	if len(hex) == 3 {
		hex = fmt.Sprintf("%s%s%s%s%s%s", string(hex[0]), string(hex[0]), string(hex[1]), string(hex[1]), string(hex[2]), string(hex[2]))
	}
	h = strings.ToUpper(hex)
	return
}

//rgb takes a hex colour and returns the rgb components
func rgb(hex string) (r, g, b int64) {
	//Don't have to check errors here as hex has to be valid hexidecimal at this poiint
	r, _ = strconv.ParseInt(hex[0:2], 16, 64)
	g, _ = strconv.ParseInt(hex[2:4], 16, 64)
	b, _ = strconv.ParseInt(hex[4:6], 16, 64)
	return
}

//hsl takes and rgb colour and returns the hsl compontents
func hsl(ri, gi, bi int64) (h, s, l float64) {
	r, g, b := float64(ri)/255, float64(gi)/255, float64(bi)/255
	min := math.Min(r, math.Min(g, b))
	max := math.Max(r, math.Max(g, b))
	delta := max - min
	l = (min + max) / 2

	//Conversion formula from http://www.rapidtables.com/convert/color/rgb-to-hsl.htm
	s = 0
	if l > 0 && l < 1 {
		if l < 0.5 {
			s = delta / (max + min)
		} else {
			s = delta / (2 - max - min)
		}
	}
	h = 0
	if delta > 0 {
		if max == r && max != g {
			h = (g - b) / delta
		} else if max == g && max != b {
			h = 2 + (b-r)/delta
		} else if max == b && max != r {
			h = 4 + (r-g)/delta
		}
		h = math.Floor((h * 60) + 0.5)
	}

	//times numbers be 100 whilst rounding them correctly (hence * 1000 then / 10)
	l = math.Floor((l*1000)+0.5) / 10
	s = math.Floor((s*1000)+0.5) / 10
	return
}

//takes hue / shade name and returns its hex code
func shade(shadename string) (hex string) {
	hex = "#000000"
	for _, v := range shades {
		if shadename == v.name {
			hex = v.hex
			return
		}
	}
	return
}

//shades is an array of general shades/hues and their hex codes.
var shades = []hueShade{
	{hex: "FF0000", name: "Red"},
	{hex: "FFA500", name: "Orange"},
	{hex: "FFFF00", name: "Yellow"},
	{hex: "008000", name: "Green"},
	{hex: "0000FF", name: "Blue"},
	{hex: "EE82EE", name: "Violet"},
	{hex: "A52A2A", name: "Brown"},
	{hex: "000000", name: "Black"},
	{hex: "808080", name: "Grey"},
	{hex: "FFFFFF", name: "White"},
}

//colours list from http://chir.ag/projects/ntc/
var colours = []colour{
	{hex: "35312C", colour: "Acadia", hue: "Brown"},
	{hex: "75AA94", colour: "Acapulco", hue: "Green"},
	{hex: "C0E8D5", colour: "Aero Blue", hue: "Green"},
	{hex: "745085", colour: "Affair", hue: "Violet"},
	{hex: "905E26", colour: "Afghan Tan", hue: "Yellow"},
	{hex: "5D8AA8", colour: "Air Force Blue", hue: "Blue"},
	{hex: "BEB29A", colour: "Akaroa", hue: "Yellow"},
	{hex: "F2F0E6", colour: "Alabaster", hue: "Grey"},
	{hex: "E1DACB", colour: "Albescent White", hue: "Yellow"},
	{hex: "954E2C", colour: "Alert Tan", hue: "Orange"},
	{hex: "F0F8FF", colour: "Alice Blue", hue: "Blue"},
	{hex: "E32636", colour: "Alizarin", hue: "Red"},
	{hex: "1F6A7D", colour: "Allports", hue: "Blue"},
	{hex: "EED9C4", colour: "Almond", hue: "Yellow"},
	{hex: "9A8678", colour: "Almond Frost", hue: "Brown"},
	{hex: "AD8A3B", colour: "Alpine", hue: "Yellow"},
	{hex: "CDC6C5", colour: "Alto", hue: "Grey"},
	{hex: "848789", colour: "Aluminium", hue: "Grey"},
	{hex: "E52B50", colour: "Amaranth", hue: "Red"},
	{hex: "387B54", colour: "Amazon", hue: "Green"},
	{hex: "FFBF00", colour: "Amber", hue: "Yellow"},
	{hex: "8A7D72", colour: "Americano", hue: "Brown"},
	{hex: "9966CC", colour: "Amethyst", hue: "Violet"},
	{hex: "95879C", colour: "Amethyst Smoke", hue: "Violet"},
	{hex: "F5E6EA", colour: "Amour", hue: "Violet"},
	{hex: "7D9D72", colour: "Amulet", hue: "Green"},
	{hex: "8CCEEA", colour: "Anakiwa", hue: "Blue"},
	{hex: "6C461F", colour: "Antique Brass", hue: "Orange"},
	{hex: "FAEBD7", colour: "Antique White", hue: "White"},
	{hex: "C68E3F", colour: "Anzac", hue: "Yellow"},
	{hex: "D3A95C", colour: "Apache", hue: "Yellow"},
	{hex: "66B348", colour: "Apple", hue: "Green"},
	{hex: "A95249", colour: "Apple Blossom", hue: "Red"},
	{hex: "DEEADC", colour: "Apple Green", hue: "Green"},
	{hex: "FBCEB1", colour: "Apricot", hue: "Orange"},
	{hex: "F7F0DB", colour: "Apricot White", hue: "Yellow"},
	{hex: "00FFFF", colour: "Aqua", hue: "Blue"},
	{hex: "D9DDD5", colour: "Aqua Haze", hue: "Grey"},
	{hex: "E8F3E8", colour: "Aqua Spring", hue: "Green"},
	{hex: "DBE4DC", colour: "Aqua Squeeze", hue: "Grey"},
	{hex: "7FFFD4", colour: "Aquamarine", hue: "Blue"},
	{hex: "274A5D", colour: "Arapawa", hue: "Blue"},
	{hex: "484A46", colour: "Armadillo", hue: "Grey"},
	{hex: "4B5320", colour: "Army green", hue: "Green"},
	{hex: "827A67", colour: "Arrowtown", hue: "Yellow"},
	{hex: "3B444B", colour: "Arsenic", hue: "Grey"},
	{hex: "BEBAA7", colour: "Ash", hue: "Green"},
	{hex: "7BA05B", colour: "Asparagus", hue: "Green"},
	{hex: "EDD5A6", colour: "Astra", hue: "Yellow"},
	{hex: "376F89", colour: "Astral", hue: "Blue"},
	{hex: "445172", colour: "Astronaut", hue: "Blue"},
	{hex: "214559", colour: "Astronaut Blue", hue: "Blue"},
	{hex: "DCDDDD", colour: "Athens Grey", hue: "Grey"},
	{hex: "D5CBB2", colour: "Aths Special", hue: "Yellow"},
	{hex: "9CD03B", colour: "Atlantis", hue: "Green"},
	{hex: "2B797A", colour: "Atoll", hue: "Green"},
	{hex: "3D4B52", colour: "Atomic", hue: "Blue"},
	{hex: "FF9966", colour: "Atomic Tangerine", hue: "Orange"},
	{hex: "9E6759", colour: "Au Chico", hue: "Brown"},
	{hex: "372528", colour: "Aubergine", hue: "Brown"},
	{hex: "712F2C", colour: "Auburn", hue: "Brown"},
	{hex: "EFF8AA", colour: "Australian Mint", hue: "Green"},
	{hex: "95986B", colour: "Avocado", hue: "Green"},
	{hex: "63775A", colour: "Axolotl", hue: "Green"},
	{hex: "F9C0C4", colour: "Azalea", hue: "Red"},
	{hex: "293432", colour: "Aztec", hue: "Green"},
	{hex: "F0FFFF", colour: "Azure", hue: "Blue"},
	{hex: "6FFFFF", colour: "Baby Blue", hue: "Blue"},
	{hex: "25597F", colour: "Bahama Blue", hue: "Blue"},
	{hex: "A9C01C", colour: "Bahia", hue: "Green"},
	{hex: "5C3317", colour: "Baker's Chocolate", hue: "Brown"},
	{hex: "849CA9", colour: "Bali Hai", hue: "Blue"},
	{hex: "3C3D3E", colour: "Baltic Sea", hue: "Grey"},
	{hex: "FBE7B2", colour: "Banana Mania", hue: "Yellow"},
	{hex: "878466", colour: "Bandicoot", hue: "Green"},
	{hex: "D2C61F", colour: "Barberry", hue: "Green"},
	{hex: "B6935C", colour: "Barley Corn", hue: "Yellow"},
	{hex: "F7E5B7", colour: "Barley White", hue: "Yellow"},
	{hex: "452E39", colour: "Barossa", hue: "Violet"},
	{hex: "2C2C32", colour: "Bastille", hue: "Blue"},
	{hex: "51574F", colour: "Battleship Grey", hue: "Grey"},
	{hex: "7BB18D", colour: "Bay Leaf", hue: "Green"},
	{hex: "353E64", colour: "Bay Of Many", hue: "Blue"},
	{hex: "8F7777", colour: "Bazaar", hue: "Brown"},
	{hex: "EBB9B3", colour: "Beauty Bush", hue: "Red"},
	{hex: "926F5B", colour: "Beaver", hue: "Brown"},
	{hex: "E9D7AB", colour: "Beeswax", hue: "Yellow"},
	{hex: "F5F5DC", colour: "Beige", hue: "Brown"},
	{hex: "86D2C1", colour: "Bermuda", hue: "Green"},
	{hex: "6F8C9F", colour: "Bermuda Grey", hue: "Blue"},
	{hex: "BCBFA8", colour: "Beryl Green", hue: "Green"},
	{hex: "F4EFE0", colour: "Bianca", hue: "Yellow"},
	{hex: "334046", colour: "Big Stone", hue: "Blue"},
	{hex: "3E8027", colour: "Bilbao", hue: "Green"},
	{hex: "AE99D2", colour: "Biloba Flower", hue: "Violet"},
	{hex: "3F3726", colour: "Birch", hue: "Yellow"},
	{hex: "D0C117", colour: "Bird Flower", hue: "Green"},
	{hex: "2F3C53", colour: "Biscay", hue: "Blue"},
	{hex: "486C7A", colour: "Bismark", hue: "Blue"},
	{hex: "B5AC94", colour: "Bison Hide", hue: "Yellow"},
	{hex: "FFE4C4", colour: "Bisque", hue: "Brown"},
	{hex: "3D2B1F", colour: "Bistre", hue: "Brown"},
	{hex: "88896C", colour: "Bitter", hue: "Green"},
	{hex: "D2DB32", colour: "Bitter Lemon", hue: "Green"},
	{hex: "FE6F5E", colour: "Bittersweet", hue: "Orange"},
	{hex: "E7D2C8", colour: "Bizarre", hue: "Orange"},
	{hex: "000000", colour: "Black", hue: "Black"},
	{hex: "232E26", colour: "Black Bean", hue: "Green"},
	{hex: "2C3227", colour: "Black Forest", hue: "Green"},
	{hex: "E0DED7", colour: "Black Haze", hue: "Grey"},
	{hex: "332C22", colour: "Black Magic", hue: "Brown"},
	{hex: "383740", colour: "Black Marlin", hue: "Blue"},
	{hex: "1E272C", colour: "Black Pearl", hue: "Blue"},
	{hex: "2C2D3C", colour: "Black Rock", hue: "Blue"},
	{hex: "532934", colour: "Black Rose", hue: "Red"},
	{hex: "24252B", colour: "Black Russian", hue: "Grey"},
	{hex: "E5E6DF", colour: "Black Squeeze", hue: "Grey"},
	{hex: "E5E4DB", colour: "Black White", hue: "Grey"},
	{hex: "43182F", colour: "Blackberry", hue: "Violet"},
	{hex: "2E183B", colour: "Blackcurrant", hue: "Violet"},
	{hex: "D9D0C1", colour: "Blanc", hue: "Yellow"},
	{hex: "FFEBCD", colour: "Blanched Almond", hue: "Brown"},
	{hex: "EBE1CE", colour: "Bleach White", hue: "Yellow"},
	{hex: "A3E3ED", colour: "Blizzard Blue", hue: "Blue"},
	{hex: "DFB1B6", colour: "Blossom", hue: "Red"},
	{hex: "0000FF", colour: "Blue", hue: "Blue"},
	{hex: "62777E", colour: "Blue Bayoux", hue: "Blue"},
	{hex: "9999CC", colour: "Blue Bell", hue: "Blue"},
	{hex: "E3D6E9", colour: "Blue Chalk", hue: "Violet"},
	{hex: "262B2F", colour: "Blue Charcoal", hue: "Blue"},
	{hex: "408F90", colour: "Blue Chill", hue: "Green"},
	{hex: "4B2D72", colour: "Blue Diamond", hue: "Violet"},
	{hex: "35514F", colour: "Blue Dianne", hue: "Green"},
	{hex: "4B3C8E", colour: "Blue Gem", hue: "Violet"},
	{hex: "BDBACE", colour: "Blue Haze", hue: "Violet"},
	{hex: "00626F", colour: "Blue Lagoon", hue: "Green"},
	{hex: "6A5BB1", colour: "Blue Marguerite", hue: "Violet"},
	{hex: "D8F0D2", colour: "Blue Romance", hue: "Green"},
	{hex: "78857A", colour: "Blue Smoke", hue: "Green"},
	{hex: "166461", colour: "Blue Stone", hue: "Green"},
	{hex: "8A2BE2", colour: "Blue Violet", hue: "Violet"},
	{hex: "1E3442", colour: "Blue Whale", hue: "Blue"},
	{hex: "3C4354", colour: "Blue Zodiac", hue: "Blue"},
	{hex: "305C71", colour: "Blumine", hue: "Blue"},
	{hex: "B55067", colour: "Blush", hue: "Red"},
	{hex: "2A2725", colour: "Bokara Grey", hue: "Grey"},
	{hex: "79443B", colour: "Bole", hue: "Brown"},
	{hex: "AEAEAD", colour: "Bombay", hue: "Grey"},
	{hex: "DFD7D2", colour: "Bon Jour", hue: "Grey"},
	{hex: "0095B6", colour: "Bondi Blue", hue: "Blue"},
	{hex: "DBC2AB", colour: "Bone", hue: "Orange"},
	{hex: "4C1C24", colour: "Bordeaux", hue: "Red"},
	{hex: "4C3D4E", colour: "Bossanova", hue: "Violet"},
	{hex: "438EAC", colour: "Boston Blue", hue: "Blue"},
	{hex: "92ACB4", colour: "Botticelli", hue: "Blue"},
	{hex: "254636", colour: "Bottle Green", hue: "Green"},
	{hex: "7C817C", colour: "Boulder", hue: "Grey"},
	{hex: "A78199", colour: "Bouquet", hue: "Violet"},
	{hex: "AF6C3E", colour: "Bourbon", hue: "Orange"},
	{hex: "5B3D27", colour: "Bracken", hue: "Brown"},
	{hex: "DCB68A", colour: "Brandy", hue: "Orange"},
	{hex: "C07C40", colour: "Brandy Punch", hue: "Orange"},
	{hex: "B6857A", colour: "Brandy Rose", hue: "Red"},
	{hex: "B5A642", colour: "Brass", hue: "Yellow"},
	{hex: "517B78", colour: "Breaker Bay", hue: "Green"},
	{hex: "C62D42", colour: "Brick Red", hue: "Red"},
	{hex: "F8EBDD", colour: "Bridal Heath", hue: "Orange"},
	{hex: "FAE6DF", colour: "Bridesmaid", hue: "Orange"},
	{hex: "66FF00", colour: "Bright Green", hue: "Green"},
	{hex: "57595D", colour: "Bright Grey", hue: "Grey"},
	{hex: "922A31", colour: "Bright Red", hue: "Red"},
	{hex: "ECBD2C", colour: "Bright Sun", hue: "Yellow"},
	{hex: "08E8DE", colour: "Bright Turquoise", hue: "Blue"},
	{hex: "FF55A3", colour: "Brilliant Rose", hue: "Red"},
	{hex: "FB607F", colour: "Brink Pink", hue: "Red"},
	{hex: "004225", colour: "British Racing Green", hue: "Green"},
	{hex: "A79781", colour: "Bronco", hue: "Brown"},
	{hex: "CD7F32", colour: "Bronze", hue: "Brown"},
	{hex: "584C25", colour: "Bronze Olive", hue: "Yellow"},
	{hex: "434C28", colour: "Bronzetone", hue: "Yellow"},
	{hex: "EECC24", colour: "Broom", hue: "Yellow"},
	{hex: "A52A2A", colour: "Brown", hue: "Brown"},
	{hex: "53331E", colour: "Brown Bramble", hue: "Brown"},
	{hex: "594537", colour: "Brown Derby", hue: "Brown"},
	{hex: "3C241B", colour: "Brown Pod", hue: "Brown"},
	{hex: "E6F2EA", colour: "Bubbles", hue: "Green"},
	{hex: "6E5150", colour: "Buccaneer", hue: "Red"},
	{hex: "A5A88F", colour: "Bud", hue: "Green"},
	{hex: "BC9B1B", colour: "Buddha Gold", hue: "Yellow"},
	{hex: "F0DC82", colour: "Buff", hue: "Yellow"},
	{hex: "482427", colour: "Bulgarian Rose", hue: "Red"},
	{hex: "75442B", colour: "Bull Shot", hue: "Orange"},
	{hex: "292C2F", colour: "Bunker", hue: "Grey"},
	{hex: "2B3449", colour: "Bunting", hue: "Blue"},
	{hex: "800020", colour: "Burgundy", hue: "Red"},
	{hex: "DEB887", colour: "Burly Wood", hue: "Brown"},
	{hex: "234537", colour: "Burnham", hue: "Green"},
	{hex: "D08363", colour: "Burning Sand", hue: "Orange"},
	{hex: "582124", colour: "Burnt Crimson", hue: "Red"},
	{hex: "FF7034", colour: "Burnt Orange", hue: "Orange"},
	{hex: "E97451", colour: "Burnt Sienna", hue: "Brown"},
	{hex: "8A3324", colour: "Burnt Umber", hue: "Brown"},
	{hex: "DA9429", colour: "Buttercup", hue: "Yellow"},
	{hex: "9D702E", colour: "Buttered Rum", hue: "Yellow"},
	{hex: "68578C", colour: "Butterfly Bush", hue: "Violet"},
	{hex: "F6E0A4", colour: "Buttermilk", hue: "Yellow"},
	{hex: "F1EBDA", colour: "Buttery White", hue: "Yellow"},
	{hex: "4A2E32", colour: "Cab Sav", hue: "Red"},
	{hex: "CD526C", colour: "Cabaret", hue: "Red"},
	{hex: "4C5544", colour: "Cabbage Pont", hue: "Green"},
	{hex: "5B6F55", colour: "Cactus", hue: "Green"},
	{hex: "5F9EA0", colour: "Cadet Blue", hue: "Blue"},
	{hex: "984961", colour: "Cadillac", hue: "Red"},
	{hex: "6A4928", colour: "Cafe Royale", hue: "Brown"},
	{hex: "D5B185", colour: "Calico", hue: "Brown"},
	{hex: "E98C3A", colour: "California", hue: "Orange"},
	{hex: "3D7188", colour: "Calypso", hue: "Blue"},
	{hex: "206937", colour: "Camarone", hue: "Green"},
	{hex: "803A4B", colour: "Camelot", hue: "Red"},
	{hex: "CCA483", colour: "Cameo", hue: "Brown"},
	{hex: "4F4D32", colour: "Camouflage", hue: "Yellow"},
	{hex: "78866B", colour: "Camouflage Green", hue: "Green"},
	{hex: "D08A9B", colour: "Can Can", hue: "Red"},
	{hex: "FFFF99", colour: "Canary", hue: "Yellow"},
	{hex: "8E5164", colour: "Cannon Pink", hue: "Red"},
	{hex: "4E5552", colour: "Cape Cod", hue: "Grey"},
	{hex: "FEE0A5", colour: "Cape Honey", hue: "Yellow"},
	{hex: "75482F", colour: "Cape Palliser", hue: "Orange"},
	{hex: "AFC182", colour: "Caper", hue: "Green"},
	{hex: "592720", colour: "Caput Mortuum", hue: "Brown"},
	{hex: "FFD59A", colour: "Caramel", hue: "Yellow"},
	{hex: "EBE5D5", colour: "Cararra", hue: "Green"},
	{hex: "1B3427", colour: "Cardin Green", hue: "Green"},
	{hex: "C41E3A", colour: "Cardinal", hue: "Red"},
	{hex: "C99AA0", colour: "Careys Pink", hue: "Red"},
	{hex: "00CC99", colour: "Caribbean Green", hue: "Green"},
	{hex: "E68095", colour: "Carissma", hue: "Red"},
	{hex: "F5F9CB", colour: "Carla", hue: "Green"},
	{hex: "960018", colour: "Carmine", hue: "Red"},
	{hex: "5B3A24", colour: "Carnaby Tan", hue: "Brown"},
	{hex: "FFA6C9", colour: "Carnation Pink", hue: "Red"},
	{hex: "F8DBE0", colour: "Carousel Pink", hue: "Red"},
	{hex: "ED9121", colour: "Carrot Orange", hue: "Orange"},
	{hex: "F0B253", colour: "Casablanca", hue: "Yellow"},
	{hex: "3F545A", colour: "Casal", hue: "Blue"},
	{hex: "8CA8A0", colour: "Cascade", hue: "Green"},
	{hex: "D1B399", colour: "Cashmere", hue: "Brown"},
	{hex: "AAB5B8", colour: "Casper", hue: "Blue"},
	{hex: "44232F", colour: "Castro", hue: "Red"},
	{hex: "273C5A", colour: "Catalina Blue", hue: "Blue"},
	{hex: "E0E4DC", colour: "Catskill White", hue: "Grey"},
	{hex: "E0B8B1", colour: "Cavern Pink", hue: "Red"},
	{hex: "9271A7", colour: "Ce Soir", hue: "Violet"},
	{hex: "463430", colour: "Cedar", hue: "Brown"},
	{hex: "ACE1AF", colour: "Celadon", hue: "Green"},
	{hex: "B4C04C", colour: "Celery", hue: "Green"},
	{hex: "D2D2C0", colour: "Celeste", hue: "Green"},
	{hex: "3A4E5F", colour: "Cello", hue: "Blue"},
	{hex: "2B3F36", colour: "Celtic", hue: "Green"},
	{hex: "857158", colour: "Cement", hue: "Brown"},
	{hex: "DE3163", colour: "Cerise", hue: "Violet"},
	{hex: "007BA7", colour: "Cerulean", hue: "Blue"},
	{hex: "2A52BE", colour: "Cerulean Blue", hue: "Blue"},
	{hex: "FDE9E0", colour: "Chablis", hue: "Red"},
	{hex: "5A6E41", colour: "Chalet Green", hue: "Green"},
	{hex: "DFC281", colour: "Chalky", hue: "Yellow"},
	{hex: "475877", colour: "Chambray", hue: "Blue"},
	{hex: "E8CD9A", colour: "Chamois", hue: "Yellow"},
	{hex: "EED9B6", colour: "Champagne", hue: "Yellow"},
	{hex: "EDB8C7", colour: "Chantilly", hue: "Red"},
	{hex: "394043", colour: "Charade", hue: "Blue"},
	{hex: "464646", colour: "Charcoal", hue: "Grey"},
	{hex: "F8EADF", colour: "Chardon", hue: "Orange"},
	{hex: "FFC878", colour: "Chardonnay", hue: "Yellow"},
	{hex: "A4DCE6", colour: "Charlotte", hue: "Blue"},
	{hex: "D0748B", colour: "Charm", hue: "Red"},
	{hex: "7FFF00", colour: "Chartreuse", hue: "Green"},
	{hex: "DFFF00", colour: "Chartreuse Yellow", hue: "Yellow"},
	{hex: "419F59", colour: "Chateau Green", hue: "Green"},
	{hex: "B3ABB6", colour: "Chatelle", hue: "Violet"},
	{hex: "2C5971", colour: "Chathams Blue", hue: "Blue"},
	{hex: "88A95B", colour: "Chelsea Cucumber", hue: "Green"},
	{hex: "95532F", colour: "Chelsea Gem", hue: "Orange"},
	{hex: "DEC371", colour: "Chenin", hue: "Yellow"},
	{hex: "F5CD82", colour: "Cherokee", hue: "Yellow"},
	{hex: "372D52", colour: "Cherry Pie", hue: "Violet"},
	{hex: "F5D7DC", colour: "Cherub", hue: "Red"},
	{hex: "B94E48", colour: "Chestnut", hue: "Brown"},
	{hex: "666FB4", colour: "Chetwode Blue", hue: "Blue"},
	{hex: "5B5D56", colour: "Chicago", hue: "Grey"},
	{hex: "F0F5BB", colour: "Chiffon", hue: "Green"},
	{hex: "D05E34", colour: "Chilean Fire", hue: "Orange"},
	{hex: "F9F7DE", colour: "Chilean Heath", hue: "Green"},
	{hex: "FBF3D3", colour: "China Ivory", hue: "Green"},
	{hex: "B8AD8A", colour: "Chino", hue: "Yellow"},
	{hex: "9DD3A8", colour: "Chinook", hue: "Green"},
	{hex: "D2691E", colour: "Chocolate", hue: "Brown"},
	{hex: "382161", colour: "Christalle", hue: "Violet"},
	{hex: "71A91D", colour: "Christi", hue: "Green"},
	{hex: "BF652E", colour: "Christine", hue: "Orange"},
	{hex: "CAC7B7", colour: "Chrome White", hue: "Green"},
	{hex: "7D4E38", colour: "Cigar", hue: "Brown"},
	{hex: "242A2E", colour: "Cinder", hue: "Grey"},
	{hex: "FBD7CC", colour: "Cinderella", hue: "Red"},
	{hex: "E34234", colour: "Cinnabar", hue: "Red"},
	{hex: "5D3B2E", colour: "Cioccolato", hue: "Brown"},
	{hex: "8E9A21", colour: "Citron", hue: "Green"},
	{hex: "9FB70A", colour: "Citrus", hue: "Green"},
	{hex: "D2B3A9", colour: "Clam Shell", hue: "Orange"},
	{hex: "6E2233", colour: "Claret", hue: "Red"},
	{hex: "F4C8DB", colour: "Classic Rose", hue: "Violet"},
	{hex: "897E59", colour: "Clay Creek", hue: "Yellow"},
	{hex: "DFEFEA", colour: "Clear Day", hue: "Green"},
	{hex: "463623", colour: "Clinker", hue: "Brown"},
	{hex: "C2BCB1", colour: "Cloud", hue: "Yellow"},
	{hex: "353E4F", colour: "Cloud Burst", hue: "Blue"},
	{hex: "B0A99F", colour: "Cloudy", hue: "Brown"},
	{hex: "47562F", colour: "Clover", hue: "Green"},
	{hex: "0047AB", colour: "Cobalt", hue: "Blue"},
	{hex: "4F3835", colour: "Cocoa Bean", hue: "Red"},
	{hex: "35281E", colour: "Cocoa Brown", hue: "Brown"},
	{hex: "E1DABB", colour: "Coconut Cream", hue: "Green"},
	{hex: "2D3032", colour: "Cod Grey", hue: "Grey"},
	{hex: "726751", colour: "Coffee", hue: "Yellow"},
	{hex: "362D26", colour: "Coffee Bean", hue: "Brown"},
	{hex: "9A463D", colour: "Cognac", hue: "Red"},
	{hex: "3C2F23", colour: "Cola", hue: "Brown"},
	{hex: "9D8ABF", colour: "Cold Purple", hue: "Violet"},
	{hex: "CAB5B2", colour: "Cold Turkey", hue: "Red"},
	{hex: "9BDDFF", colour: "Columbia Blue", hue: "Blue"},
	{hex: "636373", colour: "Comet", hue: "Blue"},
	{hex: "4C785C", colour: "Como", hue: "Green"},
	{hex: "A0B1AE", colour: "Conch", hue: "Green"},
	{hex: "827F79", colour: "Concord", hue: "Grey"},
	{hex: "D2D1CD", colour: "Concrete", hue: "Grey"},
	{hex: "DDCB46", colour: "Confetti", hue: "Green"},
	{hex: "654D49", colour: "Congo Brown", hue: "Brown"},
	{hex: "B1DD52", colour: "Conifer", hue: "Green"},
	{hex: "C16F68", colour: "Contessa", hue: "Red"},
	{hex: "DA8A67", colour: "Copper", hue: "Red"},
	{hex: "77422C", colour: "Copper Canyon", hue: "Orange"},
	{hex: "996666", colour: "Copper Rose", hue: "Violet"},
	{hex: "95524C", colour: "Copper Rust", hue: "Red"},
	{hex: "FF7F50", colour: "Coral", hue: "Orange"},
	{hex: "F5D0C9", colour: "Coral Candy", hue: "Red"},
	{hex: "FF4040", colour: "Coral Red", hue: "Red"},
	{hex: "AB6E67", colour: "Coral Tree", hue: "Red"},
	{hex: "404D49", colour: "Corduroy", hue: "Green"},
	{hex: "BBB58D", colour: "Coriander", hue: "Green"},
	{hex: "5A4C42", colour: "Cork", hue: "Brown"},
	{hex: "FBEC5D", colour: "Corn", hue: "Yellow"},
	{hex: "F8F3C4", colour: "Corn Field", hue: "Green"},
	{hex: "42426F", colour: "Corn Flower Blue", hue: "Blue"},
	{hex: "8D702A", colour: "Corn Harvest", hue: "Yellow"},
	{hex: "FFF8DC", colour: "Corn Silk", hue: "Yellow"},
	{hex: "93CCEA", colour: "Cornflower", hue: "Blue"},
	{hex: "6495ED", colour: "Cornflower Blue", hue: "Blue"},
	{hex: "E9BA81", colour: "Corvette", hue: "Orange"},
	{hex: "794D60", colour: "Cosmic", hue: "Violet"},
	{hex: "E1F8E7", colour: "Cosmic Latte", hue: "White"},
	{hex: "FCD5CF", colour: "Cosmos", hue: "Red"},
	{hex: "625D2A", colour: "Costa Del Sol", hue: "Green"},
	{hex: "FFB7D5", colour: "Cotton Candy", hue: "Red"},
	{hex: "BFBAAF", colour: "Cotton Seed", hue: "Yellow"},
	{hex: "1B4B35", colour: "County Green", hue: "Green"},
	{hex: "443736", colour: "Cowboy", hue: "Brown"},
	{hex: "87382F", colour: "Crab Apple", hue: "Red"},
	{hex: "A65648", colour: "Crail", hue: "Red"},
	{hex: "DB5079", colour: "Cranberry", hue: "Red"},
	{hex: "4D3E3C", colour: "Crater Brown", hue: "Brown"},
	{hex: "FFFDD0", colour: "Cream", hue: "White"},
	{hex: "FFE39B", colour: "Cream Brulee", hue: "Yellow"},
	{hex: "EEC051", colour: "Cream Can", hue: "Yellow"},
	{hex: "393227", colour: "Creole", hue: "Brown"},
	{hex: "77712B", colour: "Crete", hue: "Green"},
	{hex: "DC143C", colour: "Crimson", hue: "Red"},
	{hex: "706950", colour: "Crocodile", hue: "Yellow"},
	{hex: "763C33", colour: "Crown Of Thorns", hue: "Red"},
	{hex: "B4E2D5", colour: "Cruise", hue: "Green"},
	{hex: "165B31", colour: "Crusoe", hue: "Green"},
	{hex: "F38653", colour: "Crusta", hue: "Orange"},
	{hex: "784430", colour: "Cumin", hue: "Orange"},
	{hex: "F5F4C1", colour: "Cumulus", hue: "Green"},
	{hex: "F5B2C5", colour: "Cupid", hue: "Red"},
	{hex: "3D85B8", colour: "Curious Blue", hue: "Blue"},
	{hex: "5C8173", colour: "Cutty Sark", hue: "Green"},
	{hex: "0F4645", colour: "Cyprus", hue: "Green"},
	{hex: "EDD2A4", colour: "Dairy Cream", hue: "Yellow"},
	{hex: "5B3E90", colour: "Daisy Bush", hue: "Violet"},
	{hex: "664A2D", colour: "Dallas", hue: "Brown"},
	{hex: "FED85D", colour: "Dandelion", hue: "Yellow"},
	{hex: "5B89C0", colour: "Danube", hue: "Blue"},
	{hex: "00008B", colour: "Dark Blue", hue: "Blue"},
	{hex: "654321", colour: "Dark Brown", hue: "Brown"},
	{hex: "08457E", colour: "Dark Cerulean", hue: "Blue"},
	{hex: "986960", colour: "Dark Chestnut", hue: "Red"},
	{hex: "CD5B45", colour: "Dark Coral", hue: "Orange"},
	{hex: "008B8B", colour: "Dark Cyan", hue: "Green"},
	{hex: "B8860B", colour: "Dark Goldenrod", hue: "Yellow"},
	{hex: "A9A9A9", colour: "Dark Gray", hue: "Grey"},
	{hex: "013220", colour: "Dark Green", hue: "Green"},
	{hex: "4A766E", colour: "Dark Green Copper", hue: "Green"},
	{hex: "BDB76B", colour: "Dark Khaki", hue: "Yellow"},
	{hex: "8B008B", colour: "Dark Magenta", hue: "Violet"},
	{hex: "556B2F", colour: "Dark Olive Green", hue: "Green"},
	{hex: "FF8C00", colour: "Dark Orange", hue: "Orange"},
	{hex: "9932CC", colour: "Dark Orchid", hue: "Violet"},
	{hex: "03C03C", colour: "Dark Pastel Green", hue: "Green"},
	{hex: "E75480", colour: "Dark Pink", hue: "Red"},
	{hex: "871F78", colour: "Dark Purple", hue: "Violet"},
	{hex: "8B0000", colour: "Dark Red", hue: "Red"},
	{hex: "45362B", colour: "Dark Rum", hue: "Brown"},
	{hex: "E9967A", colour: "Dark Salmon", hue: "Orange"},
	{hex: "8FBC8F", colour: "Dark Sea Green", hue: "Green"},
	{hex: "465352", colour: "Dark Slate", hue: "Green"},
	{hex: "483D8B", colour: "Dark Slate Blue", hue: "Blue"},
	{hex: "2F4F4F", colour: "Dark Slate Grey", hue: "Grey"},
	{hex: "177245", colour: "Dark Spring Green", hue: "Green"},
	{hex: "97694F", colour: "Dark Tan", hue: "Brown"},
	{hex: "FFA812", colour: "Dark Tangerine", hue: "Orange"},
	{hex: "00CED1", colour: "Dark Turquoise", hue: "Blue"},
	{hex: "9400D3", colour: "Dark Violet", hue: "Violet"},
	{hex: "855E42", colour: "Dark Wood", hue: "Brown"},
	{hex: "788878", colour: "Davy's Grey", hue: "Grey"},
	{hex: "9F9D91", colour: "Dawn", hue: "Green"},
	{hex: "E6D6CD", colour: "Dawn Pink", hue: "Orange"},
	{hex: "85CA87", colour: "De York", hue: "Green"},
	{hex: "CCCF82", colour: "Deco", hue: "Green"},
	{hex: "E36F8A", colour: "Deep Blush", hue: "Red"},
	{hex: "51412D", colour: "Deep Bronze", hue: "Brown"},
	{hex: "DA3287", colour: "Deep Cerise", hue: "Violet"},
	{hex: "193925", colour: "Deep Fir", hue: "Green"},
	{hex: "343467", colour: "Deep Koamaru", hue: "Violet"},
	{hex: "9955BB", colour: "Deep Lilac", hue: "Violet"},
	{hex: "CC00CC", colour: "Deep Magenta", hue: "Violet"},
	{hex: "FF1493", colour: "Deep Pink", hue: "Red"},
	{hex: "167E65", colour: "Deep Sea", hue: "Green"},
	{hex: "00BFFF", colour: "Deep Sky Blue", hue: "Blue"},
	{hex: "19443C", colour: "Deep Teal", hue: "Green"},
	{hex: "B5998E", colour: "Del Rio", hue: "Brown"},
	{hex: "486531", colour: "Dell", hue: "Green"},
	{hex: "999B95", colour: "Delta", hue: "Grey"},
	{hex: "8272A4", colour: "Deluge", hue: "Violet"},
	{hex: "1560BD", colour: "Denim", hue: "Blue"},
	{hex: "F9E4C6", colour: "Derby", hue: "Yellow"},
	{hex: "A15F3B", colour: "Desert", hue: "Orange"},
	{hex: "EDC9AF", colour: "Desert Sand", hue: "Brown"},
	{hex: "EDE7E0", colour: "Desert Storm", hue: "Grey"},
	{hex: "E7F2E9", colour: "Dew", hue: "Green"},
	{hex: "322C2B", colour: "Diesel", hue: "Grey"},
	{hex: "696969", colour: "Dim Gray", hue: "Grey"},
	{hex: "607C47", colour: "Dingley", hue: "Green"},
	{hex: "892D4F", colour: "Disco", hue: "Red"},
	{hex: "CD8431", colour: "Dixie", hue: "Yellow"},
	{hex: "1E90FF", colour: "Dodger Blue", hue: "Blue"},
	{hex: "F5F171", colour: "Dolly", hue: "Green"},
	{hex: "6A6873", colour: "Dolphin", hue: "Violet"},
	{hex: "6C5B4C", colour: "Domino", hue: "Brown"},
	{hex: "5A4F51", colour: "Don Juan", hue: "Brown"},
	{hex: "816E5C", colour: "Donkey Brown", hue: "Brown"},
	{hex: "6E5F56", colour: "Dorado", hue: "Brown"},
	{hex: "E4CF99", colour: "Double Colonial White", hue: "Yellow"},
	{hex: "E9DCBE", colour: "Double Pearl Lusta", hue: "Yellow"},
	{hex: "D2C3A3", colour: "Double Spanish White", hue: "Yellow"},
	{hex: "777672", colour: "Dove Grey", hue: "Grey"},
	{hex: "6FD2BE", colour: "Downy", hue: "Green"},
	{hex: "FBEB9B", colour: "Drover", hue: "Yellow"},
	{hex: "514F4A", colour: "Dune", hue: "Grey"},
	{hex: "E5CAC0", colour: "Dust Storm", hue: "Orange"},
	{hex: "AC9B9B", colour: "Dusty Grey", hue: "Grey"},
	{hex: "F0DFBB", colour: "Dutch White", hue: "Yellow"},
	{hex: "B0AC94", colour: "Eagle", hue: "Green"},
	{hex: "B8A722", colour: "Earls Green", hue: "Green"},
	{hex: "FBF2DB", colour: "Early Dawn", hue: "Yellow"},
	{hex: "47526E", colour: "East Bay", hue: "Blue"},
	{hex: "AA8CBC", colour: "East Side", hue: "Violet"},
	{hex: "00879F", colour: "Eastern Blue", hue: "Blue"},
	{hex: "E6D8D4", colour: "Ebb", hue: "Red"},
	{hex: "313337", colour: "Ebony", hue: "Grey"},
	{hex: "323438", colour: "Ebony Clay", hue: "Grey"},
	{hex: "A4AFCD", colour: "Echo Blue", hue: "Blue"},
	{hex: "3F3939", colour: "Eclipse", hue: "Grey"},
	{hex: "C2B280", colour: "Ecru", hue: "Brown"},
	{hex: "D6D1C0", colour: "Ecru White", hue: "Green"},
	{hex: "C96138", colour: "Ecstasy", hue: "Orange"},
	{hex: "266255", colour: "Eden", hue: "Green"},
	{hex: "C1D8C5", colour: "Edgewater", hue: "Green"},
	{hex: "97A49A", colour: "Edward", hue: "Green"},
	{hex: "F9E4C5", colour: "Egg Sour", hue: "Yellow"},
	{hex: "990066", colour: "Eggplant", hue: "Violet"},
	{hex: "1034A6", colour: "Egyptian Blue", hue: "Blue"},
	{hex: "39392C", colour: "El Paso", hue: "Green"},
	{hex: "8F4E45", colour: "El Salva", hue: "Red"},
	{hex: "7DF9FF", colour: "Electric Blue", hue: "Blue"},
	{hex: "6600FF", colour: "Electric Indigo", hue: "Violet"},
	{hex: "CCFF00", colour: "Electric Lime", hue: "Green"},
	{hex: "BF00FF", colour: "Electric Purple", hue: "Violet"},
	{hex: "243640", colour: "Elephant", hue: "Blue"},
	{hex: "1B8A6B", colour: "Elf Green", hue: "Green"},
	{hex: "297B76", colour: "Elm", hue: "Green"},
	{hex: "50C878", colour: "Emerald", hue: "Green"},
	{hex: "6E3974", colour: "Eminence", hue: "Violet"},
	{hex: "50494A", colour: "Emperor", hue: "Grey"},
	{hex: "7C7173", colour: "Empress", hue: "Grey"},
	{hex: "29598B", colour: "Endeavour", hue: "Blue"},
	{hex: "F5D752", colour: "Energy Yellow", hue: "Yellow"},
	{hex: "274234", colour: "English Holly", hue: "Green"},
	{hex: "8BA58F", colour: "Envy", hue: "Green"},
	{hex: "DAB160", colour: "Equator", hue: "Yellow"},
	{hex: "4E312D", colour: "Espresso", hue: "Red"},
	{hex: "2D2F28", colour: "Eternity", hue: "Green"},
	{hex: "329760", colour: "Eucalyptus", hue: "Green"},
	{hex: "CDA59C", colour: "Eunry", hue: "Red"},
	{hex: "26604F", colour: "Evening Sea", hue: "Green"},
	{hex: "264334", colour: "Everglade", hue: "Green"},
	{hex: "F3E5DC", colour: "Fair Pink", hue: "Orange"},
	{hex: "6E5A5B", colour: "Falcon", hue: "Brown"},
	{hex: "C19A6B", colour: "Fallow", hue: "Brown"},
	{hex: "801818", colour: "Falu Red", hue: "Red"},
	{hex: "F2E6DD", colour: "Fantasy", hue: "Orange"},
	{hex: "625665", colour: "Fedora", hue: "Violet"},
	{hex: "A5D785", colour: "Feijoa", hue: "Green"},
	{hex: "4D5D53", colour: "Feldgrau", hue: "Grey"},
	{hex: "D19275", colour: "Feldspar", hue: "Red"},
	{hex: "63B76C", colour: "Fern", hue: "Green"},
	{hex: "4F7942", colour: "Fern Green", hue: "Green"},
	{hex: "876A68", colour: "Ferra", hue: "Brown"},
	{hex: "EACC4A", colour: "Festival", hue: "Yellow"},
	{hex: "DBE0D0", colour: "Feta", hue: "Green"},
	{hex: "B1592F", colour: "Fiery Orange", hue: "Orange"},
	{hex: "636F22", colour: "Fiji Green", hue: "Green"},
	{hex: "75785A", colour: "Finch", hue: "Green"},
	{hex: "61755B", colour: "Finlandia", hue: "Green"},
	{hex: "694554", colour: "Finn", hue: "Violet"},
	{hex: "4B5A62", colour: "Fiord", hue: "Blue"},
	{hex: "8F3F2A", colour: "Fire", hue: "Orange"},
	{hex: "B22222", colour: "Fire Brick", hue: "Red"},
	{hex: "E09842", colour: "Fire Bush", hue: "Yellow"},
	{hex: "CE1620", colour: "Fire Engine Red", hue: "Red"},
	{hex: "314643", colour: "Firefly", hue: "Green"},
	{hex: "BE5C48", colour: "Flame Pea", hue: "Orange"},
	{hex: "86282E", colour: "Flame Red", hue: "Red"},
	{hex: "EA8645", colour: "Flamenco", hue: "Orange"},
	{hex: "E1634F", colour: "Flamingo", hue: "Orange"},
	{hex: "EEDC82", colour: "Flax", hue: "Yellow"},
	{hex: "716E61", colour: "Flint", hue: "Green"},
	{hex: "7A2E4D", colour: "Flirt", hue: "Red"},
	{hex: "FFFAF0", colour: "Floral White", hue: "White"},
	{hex: "D0EAE8", colour: "Foam", hue: "Green"},
	{hex: "D5C7E8", colour: "Fog", hue: "Violet"},
	{hex: "A7A69D", colour: "Foggy Grey", hue: "Grey"},
	{hex: "228B22", colour: "Forest Green", hue: "Green"},
	{hex: "FDEFDB", colour: "Forget Me Not", hue: "Yellow"},
	{hex: "65ADB2", colour: "Fountain Blue", hue: "Blue"},
	{hex: "FFD7A0", colour: "Frangipani", hue: "Yellow"},
	{hex: "029D74", colour: "Free Speech Aquamarine", hue: "Green"},
	{hex: "4156C5", colour: "Free Speech Blue", hue: "Blue"},
	{hex: "09F911", colour: "Free Speech Green", hue: "Green"},
	{hex: "E35BD8", colour: "Free Speech Magenta", hue: "Red"},
	{hex: "C00000", colour: "Free Speech Red", hue: "Red"},
	{hex: "BFBDC1", colour: "French Grey", hue: "Grey"},
	{hex: "DEB7D9", colour: "French Lilac", hue: "Violet"},
	{hex: "A4D2E0", colour: "French Pass", hue: "Blue"},
	{hex: "F64A8A", colour: "French Rose", hue: "Red"},
	{hex: "86837A", colour: "Friar Grey", hue: "Grey"},
	{hex: "B4E1BB", colour: "Fringy Flower", hue: "Green"},
	{hex: "E56D75", colour: "Froly", hue: "Red"},
	{hex: "E1E4C5", colour: "Frost", hue: "Green"},
	{hex: "E2F2E4", colour: "Frosted Mint", hue: "Green"},
	{hex: "DBE5D2", colour: "Frostee", hue: "Green"},
	{hex: "4BA351", colour: "Fruit Salad", hue: "Green"},
	{hex: "C154C1", colour: "Fuchsia", hue: "Violet"},
	{hex: "FF77FF", colour: "Fuchsia Pink", hue: "Red"},
	{hex: "C2D62E", colour: "Fuego", hue: "Green"},
	{hex: "D19033", colour: "Fuel Yellow", hue: "Yellow"},
	{hex: "335083", colour: "Fun Blue", hue: "Blue"},
	{hex: "15633D", colour: "Fun Green", hue: "Green"},
	{hex: "3C3B3C", colour: "Fuscous Grey", hue: "Grey"},
	{hex: "C45655", colour: "Fuzzy Wuzzy Brown", hue: "Brown"},
	{hex: "2C4641", colour: "Gable Green", hue: "Green"},
	{hex: "DCDCDC", colour: "Gainsboro", hue: "White"},
	{hex: "DCD7D1", colour: "Gallery", hue: "Grey"},
	{hex: "D8A723", colour: "Galliano", hue: "Yellow"},
	{hex: "E49B0F", colour: "Gamboge", hue: "Yellow"},
	{hex: "C5832E", colour: "Geebung", hue: "Yellow"},
	{hex: "31796D", colour: "Genoa", hue: "Green"},
	{hex: "E77B75", colour: "Geraldine", hue: "Red"},
	{hex: "CBD0CF", colour: "Geyser", hue: "Grey"},
	{hex: "C0BFC7", colour: "Ghost", hue: "Blue"},
	{hex: "F8F8FF", colour: "Ghost White", hue: "White"},
	{hex: "564786", colour: "Gigas", hue: "Violet"},
	{hex: "B9AD61", colour: "Gimblet", hue: "Green"},
	{hex: "D9DFCD", colour: "Gin", hue: "Green"},
	{hex: "F8EACA", colour: "Gin Fizz", hue: "Yellow"},
	{hex: "EBD4AE", colour: "Givry", hue: "Yellow"},
	{hex: "78B1BF", colour: "Glacier", hue: "Blue"},
	{hex: "5F8151", colour: "Glade Green", hue: "Green"},
	{hex: "786E4C", colour: "Go Ben", hue: "Yellow"},
	{hex: "34533D", colour: "Goblin", hue: "Green"},
	{hex: "FFD700", colour: "Gold", hue: "Yellow"},
	{hex: "D56C30", colour: "Gold Drop", hue: "Orange"},
	{hex: "E2B227", colour: "Gold Tips", hue: "Yellow"},
	{hex: "CA8136", colour: "Golden Bell", hue: "Orange"},
	{hex: "996515", colour: "Golden Brown", hue: "Brown"},
	{hex: "F1CC2B", colour: "Golden Dream", hue: "Yellow"},
	{hex: "EBDE31", colour: "Golden Fizz", hue: "Green"},
	{hex: "F9D77E", colour: "Golden Glow", hue: "Yellow"},
	{hex: "FCC200", colour: "Golden Poppy", hue: "Yellow"},
	{hex: "EACE6A", colour: "Golden Sand", hue: "Yellow"},
	{hex: "FFC152", colour: "Golden Tainoi", hue: "Yellow"},
	{hex: "FFDF00", colour: "Golden Yellow", hue: "Yellow"},
	{hex: "DBDB70", colour: "Goldenrod", hue: "Yellow"},
	{hex: "373332", colour: "Gondola", hue: "Grey"},
	{hex: "29332B", colour: "Gordons Green", hue: "Green"},
	{hex: "FDE336", colour: "Gorse", hue: "Green"},
	{hex: "399F86", colour: "Gossamer", hue: "Green"},
	{hex: "9FD385", colour: "Gossip", hue: "Green"},
	{hex: "698890", colour: "Gothic", hue: "Blue"},
	{hex: "51559B", colour: "Governor Bay", hue: "Blue"},
	{hex: "CAB8A2", colour: "Grain Brown", hue: "Yellow"},
	{hex: "FFCD73", colour: "Grandis", hue: "Yellow"},
	{hex: "8B8265", colour: "Granite Green", hue: "Yellow"},
	{hex: "C5E7CD", colour: "Granny Apple", hue: "Green"},
	{hex: "7B948C", colour: "Granny Smith", hue: "Green"},
	{hex: "9DE093", colour: "Granny Smith Apple", hue: "Green"},
	{hex: "413D4B", colour: "Grape", hue: "Violet"},
	{hex: "383428", colour: "Graphite", hue: "Yellow"},
	{hex: "4A4B46", colour: "Gravel", hue: "Grey"},
	{hex: "008000", colour: "Green", hue: "Green"},
	{hex: "3E6334", colour: "Green House", hue: "Green"},
	{hex: "393D2A", colour: "Green Kelp", hue: "Green"},
	{hex: "526B2D", colour: "Green Leaf", hue: "Green"},
	{hex: "BFC298", colour: "Green Mist", hue: "Green"},
	{hex: "266242", colour: "Green Pea", hue: "Green"},
	{hex: "9CA664", colour: "Green Smoke", hue: "Green"},
	{hex: "A9AF99", colour: "Green Spring", hue: "Green"},
	{hex: "23414E", colour: "Green Vogue", hue: "Blue"},
	{hex: "2C2D24", colour: "Green Waterloo", hue: "Green"},
	{hex: "DEDDCB", colour: "Green White", hue: "Green"},
	{hex: "ADFF2F", colour: "Green Yellow", hue: "Green"},
	{hex: "C14D36", colour: "Grenadier", hue: "Orange"},
	{hex: "808080", colour: "Grey", hue: "Grey"},
	{hex: "9FA3A7", colour: "Grey Chateau", hue: "Grey"},
	{hex: "BDBAAE", colour: "Grey Nickel", hue: "Green"},
	{hex: "D1D3CC", colour: "Grey Nurse", hue: "Grey"},
	{hex: "A19A7F", colour: "Grey Olive", hue: "Yellow"},
	{hex: "9391A0", colour: "Grey Suit", hue: "Blue"},
	{hex: "465945", colour: "Grey-Asparagus", hue: "Green"},
	{hex: "952E31", colour: "Guardsman Red", hue: "Red"},
	{hex: "343F5C", colour: "Gulf Blue", hue: "Blue"},
	{hex: "74B2A8", colour: "Gulf Stream", hue: "Green"},
	{hex: "A4ADB0", colour: "Gull Grey", hue: "Grey"},
	{hex: "ACC9B2", colour: "Gum Leaf", hue: "Green"},
	{hex: "718F8A", colour: "Gumbo", hue: "Green"},
	{hex: "484753", colour: "Gun Powder", hue: "Violet"},
	{hex: "2C3539", colour: "Gunmetal", hue: "Blue"},
	{hex: "7A7C76", colour: "Gunsmoke", hue: "Grey"},
	{hex: "989171", colour: "Gurkha", hue: "Green"},
	{hex: "9E8022", colour: "Hacienda", hue: "Yellow"},
	{hex: "633528", colour: "Hairy Heath", hue: "Brown"},
	{hex: "2C2A35", colour: "Haiti", hue: "Violet"},
	{hex: "EDE7C8", colour: "Half And Half", hue: "Green"},
	{hex: "558F93", colour: "Half Baked", hue: "Blue"},
	{hex: "F2E5BF", colour: "Half Colonial White", hue: "Yellow"},
	{hex: "FBF0D6", colour: "Half Dutch White", hue: "Yellow"},
	{hex: "F1EAD7", colour: "Half Pearl Lusta", hue: "Yellow"},
	{hex: "E6DBC7", colour: "Half Spanish White", hue: "Yellow"},
	{hex: "E8D4A2", colour: "Hampton", hue: "Yellow"},
	{hex: "5218FA", colour: "Han Purple", hue: "Violet"},
	{hex: "3FFF00", colour: "Harlequin", hue: "Green"},
	{hex: "C93413", colour: "Harley Davidson Orange", hue: "Orange"},
	{hex: "CBCEC0", colour: "Harp", hue: "Green"},
	{hex: "EAB76A", colour: "Harvest Gold", hue: "Yellow"},
	{hex: "3B2B2C", colour: "Havana", hue: "Brown"},
	{hex: "5784C1", colour: "Havelock Blue", hue: "Blue"},
	{hex: "99522B", colour: "Hawaiian Tan", hue: "Orange"},
	{hex: "D2DAED", colour: "Hawkes Blue", hue: "Blue"},
	{hex: "4F2A2C", colour: "Heath", hue: "Red"},
	{hex: "AEBBC1", colour: "Heather", hue: "Blue"},
	{hex: "948C7E", colour: "Heathered Grey", hue: "Brown"},
	{hex: "46473E", colour: "Heavy Metal", hue: "Grey"},
	{hex: "DF73FF", colour: "Heliotrope", hue: "Violet"},
	{hex: "69684B", colour: "Hemlock", hue: "Yellow"},
	{hex: "987D73", colour: "Hemp", hue: "Brown"},
	{hex: "928C3C", colour: "Highball", hue: "Green"},
	{hex: "7A9461", colour: "Highland", hue: "Green"},
	{hex: "A7A07E", colour: "Hillary", hue: "Green"},
	{hex: "736330", colour: "Himalaya", hue: "Yellow"},
	{hex: "DFF1D6", colour: "Hint Of Green", hue: "Green"},
	{hex: "F5EFEB", colour: "Hint Of Red", hue: "Grey"},
	{hex: "F6F5D7", colour: "Hint Of Yellow", hue: "Green"},
	{hex: "49889A", colour: "Hippie Blue", hue: "Blue"},
	{hex: "608A5A", colour: "Hippie Green", hue: "Green"},
	{hex: "AB495C", colour: "Hippie Pink", hue: "Red"},
	{hex: "A1A9A8", colour: "Hit Grey", hue: "Grey"},
	{hex: "FDA470", colour: "Hit Pink", hue: "Orange"},
	{hex: "BB8E34", colour: "Hokey Pokey", hue: "Yellow"},
	{hex: "647D86", colour: "Hoki", hue: "Blue"},
	{hex: "25342B", colour: "Holly", hue: "Green"},
	{hex: "F400A1", colour: "Hollywood Cerise", hue: "Red"},
	{hex: "5C3C6D", colour: "Honey Flower", hue: "Violet"},
	{hex: "F0FFF0", colour: "Honeydew", hue: "White"},
	{hex: "E8ED69", colour: "Honeysuckle", hue: "Green"},
	{hex: "CD6D93", colour: "Hopbush", hue: "Violet"},
	{hex: "648894", colour: "Horizon", hue: "Blue"},
	{hex: "6D562C", colour: "Horses Neck", hue: "Yellow"},
	{hex: "815B28", colour: "Hot Curry", hue: "Yellow"},
	{hex: "FF00CC", colour: "Hot Magenta", hue: "Red"},
	{hex: "FF69B4", colour: "Hot Pink", hue: "Red"},
	{hex: "4E2E53", colour: "Hot Purple", hue: "Violet"},
	{hex: "A7752C", colour: "Hot Toddy", hue: "Yellow"},
	{hex: "CEEFE4", colour: "Humming Bird", hue: "Green"},
	{hex: "355E3B", colour: "Hunter Green", hue: "Green"},
	{hex: "8B7E77", colour: "Hurricane", hue: "Brown"},
	{hex: "B2994B", colour: "Husk", hue: "Yellow"},
	{hex: "AFE3D6", colour: "Ice Cold", hue: "Green"},
	{hex: "CAE1D9", colour: "Iceberg", hue: "Green"},
	{hex: "EF95AE", colour: "Illusion", hue: "Red"},
	{hex: "B0E313", colour: "Inch Worm", hue: "Green"},
	{hex: "CD5C5C", colour: "Indian Red", hue: "Red"},
	{hex: "4F301F", colour: "Indian Tan", hue: "Brown"},
	{hex: "4B0082", colour: "Indigo", hue: "Violet"},
	{hex: "9C5B34", colour: "Indochine", hue: "Orange"},
	{hex: "002FA7", colour: "International Klein Blue", hue: "Blue"},
	{hex: "FF4F00", colour: "International Orange", hue: "Orange"},
	{hex: "03B4C8", colour: "Iris Blue", hue: "Blue"},
	{hex: "62422B", colour: "Irish Coffee", hue: "Brown"},
	{hex: "CBCDCD", colour: "Iron", hue: "Grey"},
	{hex: "706E66", colour: "Ironside Grey", hue: "Grey"},
	{hex: "865040", colour: "Ironstone", hue: "Brown"},
	{hex: "009900", colour: "Islamic Green", hue: "Green"},
	{hex: "F8EDDB", colour: "Island Spice", hue: "Yellow"},
	{hex: "FFFFF0", colour: "Ivory", hue: "White"},
	{hex: "3D325D", colour: "Jacarta", hue: "Violet"},
	{hex: "413628", colour: "Jacko Bean", hue: "Brown"},
	{hex: "3D3F7D", colour: "Jacksons Purple", hue: "Violet"},
	{hex: "00A86B", colour: "Jade", hue: "Green"},
	{hex: "E27945", colour: "Jaffa", hue: "Orange"},
	{hex: "CAE7E2", colour: "Jagged Ice", hue: "Green"},
	{hex: "3F2E4C", colour: "Jagger", hue: "Violet"},
	{hex: "29292F", colour: "Jaguar", hue: "Blue"},
	{hex: "674834", colour: "Jambalaya", hue: "Brown"},
	{hex: "2F7532", colour: "Japanese Laurel", hue: "Green"},
	{hex: "CE7259", colour: "Japonica", hue: "Orange"},
	{hex: "259797", colour: "Java", hue: "Green"},
	{hex: "5F2C2F", colour: "Jazz", hue: "Red"},
	{hex: "A50B5E", colour: "Jazzberry Jam", hue: "Red"},
	{hex: "44798E", colour: "Jelly Bean", hue: "Blue"},
	{hex: "BBD0C9", colour: "Jet Stream", hue: "Green"},
	{hex: "136843", colour: "Jewel", hue: "Green"},
	{hex: "463D3E", colour: "Jon", hue: "Grey"},
	{hex: "EEF293", colour: "Jonquil", hue: "Green"},
	{hex: "7AAAE0", colour: "Jordy Blue", hue: "Blue"},
	{hex: "5D5346", colour: "Judge Grey", hue: "Brown"},
	{hex: "878785", colour: "Jumbo", hue: "Grey"},
	{hex: "29AB87", colour: "Jungle Green", hue: "Green"},
	{hex: "B0C4C4", colour: "Jungle Mist", hue: "Green"},
	{hex: "74918E", colour: "Juniper", hue: "Green"},
	{hex: "DCBFAC", colour: "Just Right", hue: "Orange"},
	{hex: "6C5E53", colour: "Kabul", hue: "Brown"},
	{hex: "245336", colour: "Kaitoke Green", hue: "Green"},
	{hex: "C5C3B0", colour: "Kangaroo", hue: "Green"},
	{hex: "2D2D24", colour: "Karaka", hue: "Green"},
	{hex: "FEDCC1", colour: "Karry", hue: "Orange"},
	{hex: "576D8E", colour: "Kashmir Blue", hue: "Blue"},
	{hex: "4CBB17", colour: "Kelly Green", hue: "Green"},
	{hex: "4D503C", colour: "Kelp", hue: "Green"},
	{hex: "6C322E", colour: "Kenyan Copper", hue: "Red"},
	{hex: "5FB69C", colour: "Keppel", hue: "Green"},
	{hex: "F0E68C", colour: "Khaki", hue: "Yellow"},
	{hex: "BFC0AB", colour: "Kidnapper", hue: "Green"},
	{hex: "3A3532", colour: "Kilamanjaro", hue: "Grey"},
	{hex: "49764F", colour: "Killarney", hue: "Green"},
	{hex: "695D87", colour: "Kimberly", hue: "Violet"},
	{hex: "583580", colour: "Kingfisher Daisy", hue: "Violet"},
	{hex: "E093AB", colour: "Kobi", hue: "Red"},
	{hex: "7B785A", colour: "Kokoda", hue: "Green"},
	{hex: "804E2C", colour: "Korma", hue: "Orange"},
	{hex: "FEB552", colour: "Koromiko", hue: "Yellow"},
	{hex: "F9D054", colour: "Kournikova", hue: "Yellow"},
	{hex: "428929", colour: "La Palma", hue: "Green"},
	{hex: "BAC00E", colour: "La Rioja", hue: "Green"},
	{hex: "C6DA36", colour: "Las Palmas", hue: "Green"},
	{hex: "C6A95E", colour: "Laser", hue: "Yellow"},
	{hex: "FFFF66", colour: "Laser Lemon", hue: "Yellow"},
	{hex: "6E8D71", colour: "Laurel", hue: "Green"},
	{hex: "E6E6FA", colour: "Lavender", hue: "Violet"},
	{hex: "CCCCFF", colour: "Lavender Blue", hue: "Blue"},
	{hex: "FFF0F5", colour: "Lavender Blush", hue: "Violet"},
	{hex: "BDBBD7", colour: "Lavender Grey", hue: "Grey"},
	{hex: "FBAED2", colour: "Lavender Pink", hue: "Red"},
	{hex: "FBA0E3", colour: "Lavender Rose", hue: "Red"},
	{hex: "7CFC00", colour: "Lawn Green", hue: "Green"},
	{hex: "906A54", colour: "Leather", hue: "Brown"},
	{hex: "FDE910", colour: "Lemon", hue: "Yellow"},
	{hex: "FFFACD", colour: "Lemon Chiffon", hue: "Yellow"},
	{hex: "968428", colour: "Lemon Ginger", hue: "Yellow"},
	{hex: "999A86", colour: "Lemon Grass", hue: "Green"},
	{hex: "2E3749", colour: "Licorice", hue: "Blue"},
	{hex: "ADD8E6", colour: "Light Blue", hue: "Blue"},
	{hex: "F08080", colour: "Light Coral", hue: "Orange"},
	{hex: "E0FFFF", colour: "Light Cyan", hue: "Blue"},
	{hex: "EEDD82", colour: "Light Goldenrod", hue: "Yellow"},
	{hex: "FAFAD2", colour: "Light Goldenrod Yellow", hue: "Yellow"},
	{hex: "90EE90", colour: "Light Green", hue: "Green"},
	{hex: "D3D3D3", colour: "Light Grey", hue: "Grey"},
	{hex: "FFB6C1", colour: "Light Pink", hue: "Red"},
	{hex: "FFA07A", colour: "Light Salmon", hue: "Orange"},
	{hex: "20B2AA", colour: "Light Sea Green", hue: "Green"},
	{hex: "87CEFA", colour: "Light Sky Blue", hue: "Blue"},
	{hex: "8470FF", colour: "Light Slate Blue", hue: "Blue"},
	{hex: "778899", colour: "Light Slate Grey", hue: "Grey"},
	{hex: "B0C4DE", colour: "Light Steel Blue", hue: "Blue"},
	{hex: "856363", colour: "Light Wood", hue: "Brown"},
	{hex: "FFFFE0", colour: "Light Yellow", hue: "Yellow"},
	{hex: "F7A233", colour: "Lightning Yellow", hue: "Yellow"},
	{hex: "C8A2C8", colour: "Lilac", hue: "Violet"},
	{hex: "9470C4", colour: "Lilac Bush", hue: "Violet"},
	{hex: "C19FB3", colour: "Lily", hue: "Violet"},
	{hex: "E9EEEB", colour: "Lily White", hue: "Grey"},
	{hex: "7AAC21", colour: "Lima", hue: "Green"},
	{hex: "00FF00", colour: "Lime", hue: "Green"},
	{hex: "32CD32", colour: "Lime Green", hue: "Green"},
	{hex: "5F9727", colour: "Limeade", hue: "Green"},
	{hex: "89AC27", colour: "Limerick", hue: "Green"},
	{hex: "FAF0E6", colour: "Linen", hue: "White"},
	{hex: "C7CDD8", colour: "Link Water", hue: "Blue"},
	{hex: "962C54", colour: "Lipstick", hue: "Red"},
	{hex: "534B4F", colour: "Liver", hue: "Brown"},
	{hex: "312A29", colour: "Livid Brown", hue: "Brown"},
	{hex: "DBD9C2", colour: "Loafer", hue: "Green"},
	{hex: "B3BBB7", colour: "Loblolly", hue: "Green"},
	{hex: "489084", colour: "Lochinvar", hue: "Green"},
	{hex: "316EA0", colour: "Lochmara", hue: "Blue"},
	{hex: "A2A580", colour: "Locust", hue: "Green"},
	{hex: "393E2E", colour: "Log Cabin", hue: "Green"},
	{hex: "9D9CB4", colour: "Logan", hue: "Blue"},
	{hex: "B9ACBB", colour: "Lola", hue: "Violet"},
	{hex: "AE94AB", colour: "London Hue", hue: "Violet"},
	{hex: "522426", colour: "Lonestar", hue: "Red"},
	{hex: "8B504B", colour: "Lotus", hue: "Brown"},
	{hex: "4C3347", colour: "Loulou", hue: "Violet"},
	{hex: "AB9A1C", colour: "Lucky", hue: "Green"},
	{hex: "292D4F", colour: "Lucky Point", hue: "Blue"},
	{hex: "4E5541", colour: "Lunar Green", hue: "Green"},
	{hex: "782E2C", colour: "Lusty", hue: "Red"},
	{hex: "AB8D3F", colour: "Luxor Gold", hue: "Yellow"},
	{hex: "697D89", colour: "Lynch", hue: "Blue"},
	{hex: "CBE8E8", colour: "Mabel", hue: "Blue"},
	{hex: "FFB97B", colour: "Macaroni And Cheese", hue: "Orange"},
	{hex: "B7E3A8", colour: "Madang", hue: "Green"},
	{hex: "2D3C54", colour: "Madison", hue: "Blue"},
	{hex: "473E23", colour: "Madras", hue: "Brown"},
	{hex: "FF00FF", colour: "Magenta", hue: "Violet"},
	{hex: "AAF0D1", colour: "Magic Mint", hue: "Green"},
	{hex: "F8F4FF", colour: "Magnolia", hue: "White"},
	{hex: "CA3435", colour: "Mahogany", hue: "Brown"},
	{hex: "A56531", colour: "Mai Tai", hue: "Orange"},
	{hex: "2A2922", colour: "Maire", hue: "Yellow"},
	{hex: "E3B982", colour: "Maize", hue: "Yellow"},
	{hex: "695F50", colour: "Makara", hue: "Brown"},
	{hex: "505555", colour: "Mako", hue: "Grey"},
	{hex: "0BDA51", colour: "Malachite", hue: "Green"},
	{hex: "97976F", colour: "Malachite Green", hue: "Green"},
	{hex: "66B7E1", colour: "Malibu", hue: "Blue"},
	{hex: "3A4531", colour: "Mallard", hue: "Green"},
	{hex: "A59784", colour: "Malta", hue: "Brown"},
	{hex: "766D7C", colour: "Mamba", hue: "Violet"},
	{hex: "8D90A1", colour: "Manatee", hue: "Blue"},
	{hex: "B57B2E", colour: "Mandalay", hue: "Yellow"},
	{hex: "8E2323", colour: "Mandarian Orange", hue: "Orange"},
	{hex: "CD525B", colour: "Mandy", hue: "Red"},
	{hex: "F5B799", colour: "Mandys Pink", hue: "Orange"},
	{hex: "E77200", colour: "Mango Tango", hue: "Orange"},
	{hex: "E2AF80", colour: "Manhattan", hue: "Orange"},
	{hex: "7FC15C", colour: "Mantis", hue: "Green"},
	{hex: "96A793", colour: "Mantle", hue: "Green"},
	{hex: "E4DB55", colour: "Manz", hue: "Green"},
	{hex: "352235", colour: "Mardi Gras", hue: "Violet"},
	{hex: "B88A3D", colour: "Marigold", hue: "Yellow"},
	{hex: "42639F", colour: "Mariner", hue: "Blue"},
	{hex: "800000", colour: "Maroon", hue: "Brown"},
	{hex: "2B2E26", colour: "Marshland", hue: "Green"},
	{hex: "B7A8A3", colour: "Martini", hue: "Brown"},
	{hex: "3C3748", colour: "Martinique", hue: "Violet"},
	{hex: "EBC881", colour: "Marzipan", hue: "Yellow"},
	{hex: "57534B", colour: "Masala", hue: "Brown"},
	{hex: "365C7D", colour: "Matisse", hue: "Blue"},
	{hex: "8E4D45", colour: "Matrix", hue: "Red"},
	{hex: "524B4B", colour: "Matterhorn", hue: "Grey"},
	{hex: "E0B0FF", colour: "Mauve", hue: "Violet"},
	{hex: "915F6D", colour: "Mauve Taupe", hue: "Red"},
	{hex: "F091A9", colour: "Mauvelous", hue: "Red"},
	{hex: "C8B1C0", colour: "Maverick", hue: "Violet"},
	{hex: "73C2FB", colour: "Maya Blue", hue: "Blue"},
	{hex: "8C6338", colour: "McKenzie", hue: "Orange"},
	{hex: "66CDAA", colour: "Medium Aquamarine", hue: "Blue"},
	{hex: "0000CD", colour: "Medium Blue", hue: "Blue"},
	{hex: "AF4035", colour: "Medium Carmine", hue: "Red"},
	{hex: "EAEAAE", colour: "Medium Goldenrod", hue: "Yellow"},
	{hex: "BA55D3", colour: "Medium Orchid", hue: "Violet"},
	{hex: "9370DB", colour: "Medium Purple", hue: "Violet"},
	{hex: "3CB371", colour: "Medium Sea Green", hue: "Green"},
	{hex: "7B68EE", colour: "Medium Slate Blue", hue: "Blue"},
	{hex: "00FA9A", colour: "Medium Spring Green", hue: "Green"},
	{hex: "48D1CC", colour: "Medium Turquoise", hue: "Blue"},
	{hex: "C71585", colour: "Medium Violet Red", hue: "Red"},
	{hex: "A68064", colour: "Medium Wood", hue: "Brown"},
	{hex: "E0B7C2", colour: "Melanie", hue: "Red"},
	{hex: "342931", colour: "Melanzane", hue: "Violet"},
	{hex: "FEBAAD", colour: "Melon", hue: "Red"},
	{hex: "C3B9DD", colour: "Melrose", hue: "Violet"},
	{hex: "D5D2D1", colour: "Mercury", hue: "Grey"},
	{hex: "E1DBD0", colour: "Merino", hue: "Yellow"},
	{hex: "4F4E48", colour: "Merlin", hue: "Grey"},
	{hex: "73343A", colour: "Merlot", hue: "Red"},
	{hex: "554A3C", colour: "Metallic Bronze", hue: "Red"},
	{hex: "6E3D34", colour: "Metallic Copper", hue: "Red"},
	{hex: "D4AF37", colour: "Metallic Gold", hue: "Yellow"},
	{hex: "BB7431", colour: "Meteor", hue: "Orange"},
	{hex: "4A3B6A", colour: "Meteorite", hue: "Violet"},
	{hex: "9B3D3D", colour: "Mexican Red", hue: "Red"},
	{hex: "666A6D", colour: "Mid Grey", hue: "Grey"},
	{hex: "21303E", colour: "Midnight", hue: "Blue"},
	{hex: "191970", colour: "Midnight Blue", hue: "Blue"},
	{hex: "21263A", colour: "Midnight Express", hue: "Blue"},
	{hex: "242E28", colour: "Midnight Moss", hue: "Green"},
	{hex: "3F3623", colour: "Mikado", hue: "Brown"},
	{hex: "F6F493", colour: "Milan", hue: "Green"},
	{hex: "9E3332", colour: "Milano Red", hue: "Red"},
	{hex: "F3E5C0", colour: "Milk Punch", hue: "Yellow"},
	{hex: "DCD9CD", colour: "Milk White", hue: "Grey"},
	{hex: "595648", colour: "Millbrook", hue: "Brown"},
	{hex: "F5F5CC", colour: "Mimosa", hue: "Green"},
	{hex: "DAEA6F", colour: "Mindaro", hue: "Green"},
	{hex: "373E41", colour: "Mine Shaft", hue: "Blue"},
	{hex: "506355", colour: "Mineral Green", hue: "Green"},
	{hex: "407577", colour: "Ming", hue: "Green"},
	{hex: "3E3267", colour: "Minsk", hue: "Violet"},
	{hex: "F5FFFA", colour: "Mint Cream", hue: "White"},
	{hex: "98FF98", colour: "Mint Green", hue: "Green"},
	{hex: "E0D8A7", colour: "Mint Julep", hue: "Green"},
	{hex: "C6EADD", colour: "Mint Tulip", hue: "Green"},
	{hex: "373F43", colour: "Mirage", hue: "Blue"},
	{hex: "A5A9B2", colour: "Mischka", hue: "Blue"},
	{hex: "BAB9A9", colour: "Mist Grey", hue: "Grey"},
	{hex: "FFE4E1", colour: "Misty Rose", hue: "Violet"},
	{hex: "605A67", colour: "Mobster", hue: "Violet"},
	{hex: "582F2B", colour: "Moccaccino", hue: "Red"},
	{hex: "FFE4B5", colour: "Moccasin", hue: "Yellow"},
	{hex: "6F372D", colour: "Mocha", hue: "Red"},
	{hex: "97463C", colour: "Mojo", hue: "Red"},
	{hex: "FF9889", colour: "Mona Lisa", hue: "Red"},
	{hex: "6B252C", colour: "Monarch", hue: "Red"},
	{hex: "554D42", colour: "Mondo", hue: "Brown"},
	{hex: "A58B6F", colour: "Mongoose", hue: "Brown"},
	{hex: "7A7679", colour: "Monsoon", hue: "Grey"},
	{hex: "393B3C", colour: "Montana", hue: "Grey"},
	{hex: "7AC5B4", colour: "Monte Carlo", hue: "Green"},
	{hex: "8378C7", colour: "Moody Blue", hue: "Violet"},
	{hex: "F5F3CE", colour: "Moon Glow", hue: "Green"},
	{hex: "CECDB8", colour: "Moon Mist", hue: "Green"},
	{hex: "C0B2D7", colour: "Moon Raker", hue: "Violet"},
	{hex: "F0C420", colour: "Moon Yellow", hue: "Yellow"},
	{hex: "9ED1D3", colour: "Morning Glory", hue: "Blue"},
	{hex: "442D21", colour: "Morocco Brown", hue: "Brown"},
	{hex: "565051", colour: "Mortar", hue: "Grey"},
	{hex: "005F5B", colour: "Mosque", hue: "Green"},
	{hex: "ADDFAD", colour: "Moss Green", hue: "Green"},
	{hex: "1AB385", colour: "Mountain Meadow", hue: "Green"},
	{hex: "A09F9C", colour: "Mountain Mist", hue: "Grey"},
	{hex: "997A8D", colour: "Mountbatten Pink", hue: "Violet"},
	{hex: "A9844F", colour: "Muddy Waters", hue: "Yellow"},
	{hex: "9E7E53", colour: "Muesli", hue: "Brown"},
	{hex: "C54B8C", colour: "Mulberry", hue: "Violet"},
	{hex: "884F40", colour: "Mule Fawn", hue: "Brown"},
	{hex: "524D5B", colour: "Mulled Wine", hue: "Violet"},
	{hex: "FFDB58", colour: "Mustard", hue: "Yellow"},
	{hex: "D68B80", colour: "My Pink", hue: "Red"},
	{hex: "FDAE45", colour: "My Sin", hue: "Yellow"},
	{hex: "21421E", colour: "Myrtle", hue: "Green"},
	{hex: "D8DDDA", colour: "Mystic", hue: "Grey"},
	{hex: "4E5D4E", colour: "Nandor", hue: "Green"},
	{hex: "A39A87", colour: "Napa", hue: "Yellow"},
	{hex: "E9E6DC", colour: "Narvik", hue: "Green"},
	{hex: "FFDEAD", colour: "Navajo White", hue: "Brown"},
	{hex: "000080", colour: "Navy", hue: "Blue"},
	{hex: "0066CC", colour: "Navy Blue", hue: "Blue"},
	{hex: "B8C6BE", colour: "Nebula", hue: "Green"},
	{hex: "EEC7A2", colour: "Negroni", hue: "Orange"},
	{hex: "4D4DFF", colour: "Neon Blue", hue: "Blue"},
	{hex: "FF9933", colour: "Neon Carrot", hue: "Orange"},
	{hex: "FF6EC7", colour: "Neon Pink", hue: "Violet"},
	{hex: "93AAB9", colour: "Nepal", hue: "Blue"},
	{hex: "77A8AB", colour: "Neptune", hue: "Green"},
	{hex: "252525", colour: "Nero", hue: "Grey"},
	{hex: "AAA583", colour: "Neutral Green", hue: "Green"},
	{hex: "666F6F", colour: "Nevada", hue: "Grey"},
	{hex: "6D3B24", colour: "New Amber", hue: "Orange"},
	{hex: "00009C", colour: "New Midnight Blue", hue: "Blue"},
	{hex: "E4C385", colour: "New Orleans", hue: "Yellow"},
	{hex: "EBC79E", colour: "New Tan", hue: "Brown"},
	{hex: "DD8374", colour: "New York Pink", hue: "Red"},
	{hex: "29A98B", colour: "Niagara", hue: "Green"},
	{hex: "332E2E", colour: "Night Rider", hue: "Grey"},
	{hex: "A23D54", colour: "Night Shadz", hue: "Red"},
	{hex: "253F4E", colour: "Nile Blue", hue: "Blue"},
	{hex: "A99D9D", colour: "Nobel", hue: "Grey"},
	{hex: "A19986", colour: "Nomad", hue: "Yellow"},
	{hex: "1D393C", colour: "Nordic", hue: "Blue"},
	{hex: "A4B88F", colour: "Norway", hue: "Green"},
	{hex: "BC9229", colour: "Nugget", hue: "Yellow"},
	{hex: "7E4A3B", colour: "Nutmeg", hue: "Brown"},
	{hex: "FCEDC5", colour: "Oasis", hue: "Yellow"},
	{hex: "008F70", colour: "Observatory", hue: "Green"},
	{hex: "4CA973", colour: "Ocean Green", hue: "Green"},
	{hex: "CC7722", colour: "Ochre", hue: "Brown"},
	{hex: "DFF0E2", colour: "Off Green", hue: "Green"},
	{hex: "FAF3DC", colour: "Off Yellow", hue: "Yellow"},
	{hex: "313330", colour: "Oil", hue: "Grey"},
	{hex: "8A3335", colour: "Old Brick", hue: "Red"},
	{hex: "73503B", colour: "Old Copper", hue: "Red"},
	{hex: "CFB53B", colour: "Old Gold", hue: "Yellow"},
	{hex: "FDF5E6", colour: "Old Lace", hue: "White"},
	{hex: "796878", colour: "Old Lavender", hue: "Violet"},
	{hex: "C02E4C", colour: "Old Rose", hue: "Red"},
	{hex: "808000", colour: "Olive", hue: "Green"},
	{hex: "6B8E23", colour: "Olive Drab", hue: "Green"},
	{hex: "B5B35C", colour: "Olive Green", hue: "Green"},
	{hex: "888064", colour: "Olive Haze", hue: "Yellow"},
	{hex: "747028", colour: "Olivetone", hue: "Green"},
	{hex: "9AB973", colour: "Olivine", hue: "Orange"},
	{hex: "C2E6EC", colour: "Onahau", hue: "Blue"},
	{hex: "48412B", colour: "Onion", hue: "Yellow"},
	{hex: "A8C3BC", colour: "Opal", hue: "Green"},
	{hex: "987E7E", colour: "Opium", hue: "Brown"},
	{hex: "395555", colour: "Oracle", hue: "Green"},
	{hex: "FFA500", colour: "Orange", hue: "Orange"},
	{hex: "FFA000", colour: "Orange Peel", hue: "Orange"},
	{hex: "FF4500", colour: "Orange Red", hue: "Orange"},
	{hex: "A85335", colour: "Orange Roughy", hue: "Orange"},
	{hex: "EAE3CD", colour: "Orange White", hue: "Yellow"},
	{hex: "DA70D6", colour: "Orchid", hue: "Violet"},
	{hex: "F1EBD9", colour: "Orchid White", hue: "Yellow"},
	{hex: "255B77", colour: "Orient", hue: "Blue"},
	{hex: "C28E88", colour: "Oriental Pink", hue: "Red"},
	{hex: "D2D3B3", colour: "Orinoco", hue: "Green"},
	{hex: "818988", colour: "Oslo Grey", hue: "Grey"},
	{hex: "D3DBCB", colour: "Ottoman", hue: "Green"},
	{hex: "2D383A", colour: "Outer Space", hue: "Grey"},
	{hex: "FF6037", colour: "Outrageous Orange", hue: "Orange"},
	{hex: "28353A", colour: "Oxford Blue", hue: "Blue"},
	{hex: "6D9A78", colour: "Oxley", hue: "Green"},
	{hex: "D1EAEA", colour: "Oyster Bay", hue: "Blue"},
	{hex: "D4B5B0", colour: "Oyster Pink", hue: "Red"},
	{hex: "864B36", colour: "Paarl", hue: "Orange"},
	{hex: "7A715C", colour: "Pablo", hue: "Yellow"},
	{hex: "009DC4", colour: "Pacific Blue", hue: "Blue"},
	{hex: "4F4037", colour: "Paco", hue: "Brown"},
	{hex: "7EB394", colour: "Padua", hue: "Green"},
	{hex: "682860", colour: "Palatinate Purple", hue: "Violet"},
	{hex: "987654", colour: "Pale Brown", hue: "Brown"},
	{hex: "DDADAF", colour: "Pale Chestnut", hue: "Red"},
	{hex: "ABCDEF", colour: "Pale Cornflower Blue", hue: "Blue"},
	{hex: "EEE8AA", colour: "Pale Goldenrod", hue: "Yellow"},
	{hex: "98FB98", colour: "Pale Green", hue: "Green"},
	{hex: "BDCAA8", colour: "Pale Leaf", hue: "Green"},
	{hex: "F984E5", colour: "Pale Magenta", hue: "Violet"},
	{hex: "9C8D72", colour: "Pale Oyster", hue: "Brown"},
	{hex: "FADADD", colour: "Pale Pink", hue: "Red"},
	{hex: "F9F59F", colour: "Pale Prim", hue: "Green"},
	{hex: "EFD6DA", colour: "Pale Rose", hue: "Red"},
	{hex: "636D70", colour: "Pale Sky", hue: "Blue"},
	{hex: "C3BEBB", colour: "Pale Slate", hue: "Grey"},
	{hex: "BC987E", colour: "Pale Taupe", hue: "Grey"},
	{hex: "AFEEEE", colour: "Pale Turquoise", hue: "Blue"},
	{hex: "DB7093", colour: "Pale Violet Red", hue: "Red"},
	{hex: "20392C", colour: "Palm Green", hue: "Green"},
	{hex: "36482F", colour: "Palm Leaf", hue: "Green"},
	{hex: "EAE4DC", colour: "Pampas", hue: "Grey"},
	{hex: "EBF7E4", colour: "Panache", hue: "Green"},
	{hex: "DFB992", colour: "Pancho", hue: "Orange"},
	{hex: "544F3A", colour: "Panda", hue: "Yellow"},
	{hex: "FFEFD5", colour: "Papaya Whip", hue: "Yellow"},
	{hex: "7C2D37", colour: "Paprika", hue: "Red"},
	{hex: "488084", colour: "Paradiso", hue: "Green"},
	{hex: "D0C8B0", colour: "Parchment", hue: "Yellow"},
	{hex: "FBEB50", colour: "Paris Daisy", hue: "Green"},
	{hex: "312760", colour: "Paris M", hue: "Violet"},
	{hex: "BFCDC0", colour: "Paris White", hue: "Green"},
	{hex: "305D35", colour: "Parsley", hue: "Green"},
	{hex: "77DD77", colour: "Pastel Green", hue: "Green"},
	{hex: "639283", colour: "Patina", hue: "Green"},
	{hex: "D3E5EF", colour: "Pattens Blue", hue: "Blue"},
	{hex: "2A2551", colour: "Paua", hue: "Violet"},
	{hex: "BAAB87", colour: "Pavlova", hue: "Yellow"},
	{hex: "404048", colour: "Payne's Grey", hue: "Grey"},
	{hex: "FFCBA4", colour: "Peach", hue: "Orange"},
	{hex: "FFDAB9", colour: "Peach Puff", hue: "Yellow"},
	{hex: "FFCC99", colour: "Peach-Orange", hue: "Orange"},
	{hex: "FADFAD", colour: "Peach-Yellow", hue: "Yellow"},
	{hex: "7A4434", colour: "Peanut", hue: "Brown"},
	{hex: "D1E231", colour: "Pear", hue: "Yellow"},
	{hex: "DED1C6", colour: "Pearl Bush", hue: "Orange"},
	{hex: "EAE0C8", colour: "Pearl Lusta", hue: "Yellow"},
	{hex: "766D52", colour: "Peat", hue: "Yellow"},
	{hex: "2599B2", colour: "Pelorous", hue: "Blue"},
	{hex: "D7E7D0", colour: "Peppermint", hue: "Green"},
	{hex: "ACB9E8", colour: "Perano", hue: "Blue"},
	{hex: "C2A9DB", colour: "Perfume", hue: "Violet"},
	{hex: "ACB6B2", colour: "Periglacial Blue", hue: "Green"},
	{hex: "C3CDE6", colour: "Periwinkle", hue: "Blue"},
	{hex: "1C39BB", colour: "Persian Blue", hue: "Blue"},
	{hex: "00A693", colour: "Persian Green", hue: "Green"},
	{hex: "32127A", colour: "Persian Indigo", hue: "Violet"},
	{hex: "F77FBE", colour: "Persian Pink", hue: "Red"},
	{hex: "683332", colour: "Persian Plum", hue: "Red"},
	{hex: "CC3333", colour: "Persian Red", hue: "Red"},
	{hex: "FE28A2", colour: "Persian Rose", hue: "Red"},
	{hex: "EC5800", colour: "Persimmon", hue: "Red"},
	{hex: "CD853F", colour: "Peru", hue: "Brown"},
	{hex: "733D1F", colour: "Peru Tan", hue: "Orange"},
	{hex: "7A7229", colour: "Pesto", hue: "Yellow"},
	{hex: "DA9790", colour: "Petite Orchid", hue: "Red"},
	{hex: "91A092", colour: "Pewter", hue: "Green"},
	{hex: "826663", colour: "Pharlap", hue: "Brown"},
	{hex: "F8EA97", colour: "Picasso", hue: "Green"},
	{hex: "5BA0D0", colour: "Picton Blue", hue: "Blue"},
	{hex: "FDD7E4", colour: "Pig Pink", hue: "Red"},
	{hex: "00A550", colour: "Pigment Green", hue: "Green"},
	{hex: "756556", colour: "Pine Cone", hue: "Brown"},
	{hex: "BDC07E", colour: "Pine Glade", hue: "Green"},
	{hex: "01796F", colour: "Pine Green", hue: "Green"},
	{hex: "2A2F23", colour: "Pine Tree", hue: "Green"},
	{hex: "FFC0CB", colour: "Pink", hue: "Red"},
	{hex: "FF66FF", colour: "Pink Flamingo", hue: "Red"},
	{hex: "D8B4B6", colour: "Pink Flare", hue: "Red"},
	{hex: "F6CCD7", colour: "Pink Lace", hue: "Red"},
	{hex: "F3D7B6", colour: "Pink Lady", hue: "Orange"},
	{hex: "BFB3B2", colour: "Pink Swan", hue: "Grey"},
	{hex: "9D5432", colour: "Piper", hue: "Orange"},
	{hex: "F5E6C4", colour: "Pipi", hue: "Yellow"},
	{hex: "FCDBD2", colour: "Pippin", hue: "Red"},
	{hex: "BA782A", colour: "Pirate Gold", hue: "Yellow"},
	{hex: "BBCDA5", colour: "Pixie Green", hue: "Green"},
	{hex: "E57F3D", colour: "Pizazz", hue: "Orange"},
	{hex: "BF8D3C", colour: "Pizza", hue: "Yellow"},
	{hex: "3E594C", colour: "Plantation", hue: "Green"},
	{hex: "DDA0DD", colour: "Plum", hue: "Violet"},
	{hex: "651C26", colour: "Pohutukawa", hue: "Red"},
	{hex: "E5F2E7", colour: "Polar", hue: "Green"},
	{hex: "8AA7CC", colour: "Polo Blue", hue: "Blue"},
	{hex: "6A1F44", colour: "Pompadour", hue: "Violet"},
	{hex: "DDDCDB", colour: "Porcelain", hue: "Grey"},
	{hex: "DF9D5B", colour: "Porsche", hue: "Orange"},
	{hex: "3B436C", colour: "Port Gore", hue: "Blue"},
	{hex: "F4F09B", colour: "Portafino", hue: "Green"},
	{hex: "8B98D8", colour: "Portage", hue: "Blue"},
	{hex: "F0D555", colour: "Portica", hue: "Yellow"},
	{hex: "EFDCD4", colour: "Pot Pourri", hue: "Orange"},
	{hex: "845C40", colour: "Potters Clay", hue: "Brown"},
	{hex: "B0E0E6", colour: "Powder Blue", hue: "Blue"},
	{hex: "883C32", colour: "Prairie Sand", hue: "Red"},
	{hex: "CAB4D4", colour: "Prelude", hue: "Violet"},
	{hex: "E2CDD5", colour: "Prim", hue: "Violet"},
	{hex: "E4DE8E", colour: "Primrose", hue: "Green"},
	{hex: "F8F6DF", colour: "Promenade", hue: "Green"},
	{hex: "F6E3DA", colour: "Provincial Pink", hue: "Orange"},
	{hex: "003366", colour: "Prussian Blue", hue: "Blue"},
	{hex: "DD00FF", colour: "Psychedelic Purple", hue: "Violet"},
	{hex: "CC8899", colour: "Puce", hue: "Red"},
	{hex: "6E3326", colour: "Pueblo", hue: "Orange"},
	{hex: "59BAA3", colour: "Puerto Rico", hue: "Green"},
	{hex: "BAC0B4", colour: "Pumice", hue: "Green"},
	{hex: "FF7518", colour: "Pumpkin", hue: "Orange"},
	{hex: "534931", colour: "Punga", hue: "Yellow"},
	{hex: "800080", colour: "Purple", hue: "Violet"},
	{hex: "652DC1", colour: "Purple Heart", hue: "Violet"},
	{hex: "9678B6", colour: "Purple Mountain's Majesty", hue: "Violet"},
	{hex: "50404D", colour: "Purple Taupe", hue: "Grey"},
	{hex: "CDAE70", colour: "Putty", hue: "Yellow"},
	{hex: "F2EDDD", colour: "Quarter Pearl Lusta", hue: "Green"},
	{hex: "EBE2D2", colour: "Quarter Spanish White", hue: "Yellow"},
	{hex: "D9D9F3", colour: "Quartz", hue: "White"},
	{hex: "C3988B", colour: "Quicksand", hue: "Brown"},
	{hex: "CBC9C0", colour: "Quill Grey", hue: "Grey"},
	{hex: "6A5445", colour: "Quincy", hue: "Brown"},
	{hex: "232F2C", colour: "Racing Green", hue: "Green"},
	{hex: "FF355E", colour: "Radical Red", hue: "Red"},
	{hex: "DCC6A0", colour: "Raffia", hue: "Yellow"},
	{hex: "667028", colour: "Rain Forest", hue: "Green"},
	{hex: "B3C1B1", colour: "Rainee", hue: "Green"},
	{hex: "FCAE60", colour: "Rajah", hue: "Orange"},
	{hex: "2B2E25", colour: "Rangoon Green", hue: "Green"},
	{hex: "6F747B", colour: "Raven", hue: "Blue"},
	{hex: "D27D46", colour: "Raw Sienna", hue: "Brown"},
	{hex: "734A12", colour: "Raw Umber", hue: "Brown"},
	{hex: "FF33CC", colour: "Razzle Dazzle Rose", hue: "Red"},
	{hex: "E30B5C", colour: "Razzmatazz", hue: "Red"},
	{hex: "453430", colour: "Rebel", hue: "Brown"},
	{hex: "FF0000", colour: "Red", hue: "Red"},
	{hex: "701F28", colour: "Red Berry", hue: "Red"},
	{hex: "CB6F4A", colour: "Red Damask", hue: "Orange"},
	{hex: "662A2C", colour: "Red Devil", hue: "Red"},
	{hex: "FF3F34", colour: "Red Orange", hue: "Orange"},
	{hex: "5D1F1E", colour: "Red Oxide", hue: "Red"},
	{hex: "7D4138", colour: "Red Robin", hue: "Red"},
	{hex: "AD522E", colour: "Red Stage", hue: "Orange"},
	{hex: "BB3385", colour: "Medium Red Violet", hue: "Violet"},
	{hex: "5B342E", colour: "Redwood", hue: "Red"},
	{hex: "D1EF9F", colour: "Reef", hue: "Green"},
	{hex: "A98D36", colour: "Reef Gold", hue: "Yellow"},
	{hex: "203F58", colour: "Regal Blue", hue: "Blue"},
	{hex: "798488", colour: "Regent Grey", hue: "Blue"},
	{hex: "A0CDD9", colour: "Regent St Blue", hue: "Blue"},
	{hex: "F6DEDA", colour: "Remy", hue: "Red"},
	{hex: "B26E33", colour: "Reno Sand", hue: "Orange"},
	{hex: "323F75", colour: "Resolution Blue", hue: "Blue"},
	{hex: "37363F", colour: "Revolver", hue: "Violet"},
	{hex: "3D4653", colour: "Rhino", hue: "Blue"},
	{hex: "EFECDE", colour: "Rice Cake", hue: "Green"},
	{hex: "EFF5D1", colour: "Rice Flower", hue: "Green"},
	{hex: "5959AB", colour: "Rich Blue", hue: "Blue"},
	{hex: "A15226", colour: "Rich Gold", hue: "Orange"},
	{hex: "B7C61A", colour: "Rio Grande", hue: "Green"},
	{hex: "89D9C8", colour: "Riptide", hue: "Green"},
	{hex: "556061", colour: "River Bed", hue: "Blue"},
	{hex: "DDAD56", colour: "Rob Roy", hue: "Yellow"},
	{hex: "00CCCC", colour: "Robin's Egg Blue", hue: "Blue"},
	{hex: "5A4D41", colour: "Rock", hue: "Brown"},
	{hex: "93A2BA", colour: "Rock Blue", hue: "Blue"},
	{hex: "9D442D", colour: "Rock Spray", hue: "Orange"},
	{hex: "C7A384", colour: "Rodeo Dust", hue: "Brown"},
	{hex: "6D7876", colour: "Rolling Stone", hue: "Green"},
	{hex: "D8625B", colour: "Roman", hue: "Red"},
	{hex: "7D6757", colour: "Roman Coffee", hue: "Brown"},
	{hex: "F4F0E6", colour: "Romance", hue: "Grey"},
	{hex: "FFC69E", colour: "Romantic", hue: "Orange"},
	{hex: "EAB852", colour: "Ronchi", hue: "Yellow"},
	{hex: "A14743", colour: "Roof Terracotta", hue: "Red"},
	{hex: "8E593C", colour: "Rope", hue: "Orange"},
	{hex: "D3A194", colour: "Rose", hue: "Red"},
	{hex: "FEAB9A", colour: "Rose Bud", hue: "Red"},
	{hex: "8A2D52", colour: "Rose Bud Cherry", hue: "Red"},
	{hex: "AC512D", colour: "Rose Of Sharon", hue: "Orange"},
	{hex: "905D5D", colour: "Rose Taupe", hue: "Violet"},
	{hex: "FBEEE8", colour: "Rose White", hue: "Red"},
	{hex: "BC8F8F", colour: "Rosy Brown", hue: "Brown"},
	{hex: "B69642", colour: "Roti", hue: "Yellow"},
	{hex: "A94064", colour: "Rouge", hue: "Red"},
	{hex: "4169E1", colour: "Royal Blue", hue: "Blue"},
	{hex: "B54B73", colour: "Royal Heath", hue: "Red"},
	{hex: "6B3FA0", colour: "Royal Purple", hue: "Violet"},
	{hex: "E0115F", colour: "Ruby", hue: "Red"},
	{hex: "716675", colour: "Rum", hue: "Violet"},
	{hex: "F1EDD4", colour: "Rum Swizzle", hue: "Green"},
	{hex: "80461B", colour: "Russet", hue: "Brown"},
	{hex: "7D655C", colour: "Russett", hue: "Brown"},
	{hex: "B7410E", colour: "Rust", hue: "Red"},
	{hex: "3A181A", colour: "Rustic Red", hue: "Red"},
	{hex: "8D5F2C", colour: "Rusty Nail", hue: "Orange"},
	{hex: "5D4E46", colour: "Saddle", hue: "Brown"},
	{hex: "8B4513", colour: "Saddle Brown", hue: "Brown"},
	{hex: "FF6600", colour: "Safety Orange", hue: "Orange"},
	{hex: "F4C430", colour: "Saffron", hue: "Yellow"},
	{hex: "989F7A", colour: "Sage", hue: "Green"},
	{hex: "B79826", colour: "Sahara", hue: "Yellow"},
	{hex: "A5CEEC", colour: "Sail", hue: "Blue"},
	{hex: "177B4D", colour: "Salem", hue: "Green"},
	{hex: "FA8072", colour: "Salmon", hue: "Red"},
	{hex: "FFD67B", colour: "Salomie", hue: "Yellow"},
	{hex: "696268", colour: "Salt Box", hue: "Violet"},
	{hex: "EEF3E5", colour: "Saltpan", hue: "Grey"},
	{hex: "3B2E25", colour: "Sambuca", hue: "Brown"},
	{hex: "2C6E31", colour: "San Felix", hue: "Green"},
	{hex: "445761", colour: "San Juan", hue: "Blue"},
	{hex: "4E6C9D", colour: "San Marino", hue: "Blue"},
	{hex: "867665", colour: "Sand Dune", hue: "Brown"},
	{hex: "A3876A", colour: "Sandal", hue: "Brown"},
	{hex: "AF937D", colour: "Sandrift", hue: "Brown"},
	{hex: "786D5F", colour: "Sandstone", hue: "Brown"},
	{hex: "DECB81", colour: "Sandwisp", hue: "Yellow"},
	{hex: "FEDBB7", colour: "Sandy Beach", hue: "Orange"},
	{hex: "F4A460", colour: "Sandy Brown", hue: "Brown"},
	{hex: "92000A", colour: "Sangria", hue: "Red"},
	{hex: "6C3736", colour: "Sanguine Brown", hue: "Red"},
	{hex: "9998A7", colour: "Santas Grey", hue: "Blue"},
	{hex: "A96A50", colour: "Sante Fe", hue: "Orange"},
	{hex: "E1D5A6", colour: "Sapling", hue: "Yellow"},
	{hex: "082567", colour: "Sapphire", hue: "Blue"},
	{hex: "555B2C", colour: "Saratoga", hue: "Green"},
	{hex: "F4EAE4", colour: "Sauvignon", hue: "Red"},
	{hex: "F5DEC4", colour: "Sazerac", hue: "Orange"},
	{hex: "6F63A0", colour: "Scampi", hue: "Violet"},
	{hex: "ADD9D1", colour: "Scandal", hue: "Green"},
	{hex: "FF2400", colour: "Scarlet", hue: "Red"},
	{hex: "4A2D57", colour: "Scarlet Gum", hue: "Violet"},
	{hex: "7E2530", colour: "Scarlett", hue: "Red"},
	{hex: "6B6A6C", colour: "Scarpa Flow", hue: "Grey"},
	{hex: "87876F", colour: "Schist", hue: "Green"},
	{hex: "FFD800", colour: "School Bus Yellow", hue: "Yellow"},
	{hex: "8D8478", colour: "Schooner", hue: "Brown"},
	{hex: "308EA0", colour: "Scooter", hue: "Blue"},
	{hex: "6A6466", colour: "Scorpion", hue: "Grey"},
	{hex: "EEE7C8", colour: "Scotch Mist", hue: "Yellow"},
	{hex: "66FF66", colour: "Screamin' Green", hue: "Green"},
	{hex: "3D4031", colour: "Scrub", hue: "Green"},
	{hex: "EF9548", colour: "Sea Buckthorn", hue: "Orange"},
	{hex: "DFDDD6", colour: "Sea Fog", hue: "Grey"},
	{hex: "2E8B57", colour: "Sea Green", hue: "Green"},
	{hex: "C2D5C4", colour: "Sea Mist", hue: "Green"},
	{hex: "8AAEA4", colour: "Sea Nymph", hue: "Green"},
	{hex: "DB817E", colour: "Sea Pink", hue: "Red"},
	{hex: "77B7D0", colour: "Seagull", hue: "Blue"},
	{hex: "321414", colour: "Seal Brown", hue: "Brown"},
	{hex: "69326E", colour: "Seance", hue: "Violet"},
	{hex: "FFF5EE", colour: "Seashell", hue: "White"},
	{hex: "37412A", colour: "Seaweed", hue: "Green"},
	{hex: "E6DFE7", colour: "Selago", hue: "Violet"},
	{hex: "FFBA00", colour: "Selective Yellow", hue: "Yellow"},
	{hex: "6B4226", colour: "Semi-Sweet Chocolate", hue: "Brown"},
	{hex: "9E5B40", colour: "Sepia", hue: "Brown"},
	{hex: "FCE9D7", colour: "Serenade", hue: "Orange"},
	{hex: "837050", colour: "Shadow", hue: "Green"},
	{hex: "9AC0B6", colour: "Shadow Green", hue: "Green"},
	{hex: "9F9B9D", colour: "Shady Lady", hue: "Grey"},
	{hex: "609AB8", colour: "Shakespeare", hue: "Blue"},
	{hex: "F8F6A8", colour: "Shalimar", hue: "Green"},
	{hex: "33CC99", colour: "Shamrock", hue: "Green"},
	{hex: "009E60", colour: "Shamrock Green", hue: "Green"},
	{hex: "34363A", colour: "Shark", hue: "Grey"},
	{hex: "00494E", colour: "Sherpa Blue", hue: "Green"},
	{hex: "1B4636", colour: "Sherwood Green", hue: "Green"},
	{hex: "E6B2A6", colour: "Shilo", hue: "Red"},
	{hex: "745937", colour: "Shingle Fawn", hue: "Brown"},
	{hex: "7988AB", colour: "Ship Cove", hue: "Blue"},
	{hex: "4E4E4C", colour: "Ship Grey", hue: "Grey"},
	{hex: "842833", colour: "Shiraz", hue: "Red"},
	{hex: "E899BE", colour: "Shocking", hue: "Violet"},
	{hex: "FC0FC0", colour: "Shocking Pink", hue: "Red"},
	{hex: "61666B", colour: "Shuttle Grey", hue: "Grey"},
	{hex: "686B50", colour: "Siam", hue: "Green"},
	{hex: "E9D9A9", colour: "Sidecar", hue: "Yellow"},
	{hex: "A0522D", colour: "Sienna", hue: "Brown"},
	{hex: "BBADA1", colour: "Silk", hue: "Brown"},
	{hex: "C0C0C0", colour: "Silver", hue: "Grey"},
	{hex: "ACAEA9", colour: "Silver Chalice", hue: "Grey"},
	{hex: "BEBDB6", colour: "Silver Sand", hue: "Grey"},
	{hex: "67BE90", colour: "Silver Tree", hue: "Green"},
	{hex: "A6D5D0", colour: "Sinbad", hue: "Green"},
	{hex: "69293B", colour: "Siren", hue: "Red"},
	{hex: "68766E", colour: "Sirocco", hue: "Green"},
	{hex: "C5BAA0", colour: "Sisal", hue: "Yellow"},
	{hex: "9DB4AA", colour: "Skeptic", hue: "Green"},
	{hex: "87CEEB", colour: "Sky Blue", hue: "Blue"},
	{hex: "6A5ACD", colour: "Slate Blue", hue: "Blue"},
	{hex: "708090", colour: "Slate Grey", hue: "Grey"},
	{hex: "42342B", colour: "Slugger", hue: "Brown"},
	{hex: "003399", colour: "Smalt", hue: "Blue"},
	{hex: "496267", colour: "Smalt Blue", hue: "Blue"},
	{hex: "BB5F34", colour: "Smoke Tree", hue: "Orange"},
	{hex: "605D6B", colour: "Smoky", hue: "Violet"},
	{hex: "FFFAFA", colour: "Snow", hue: "White"},
	{hex: "E3E3DC", colour: "Snow Drift", hue: "Grey"},
	{hex: "EAF7C9", colour: "Snow Flurry", hue: "Green"},
	{hex: "D6F0CD", colour: "Snowy Mint", hue: "Green"},
	{hex: "E4D7E5", colour: "Snuff", hue: "Violet"},
	{hex: "ECE5DA", colour: "Soapstone", hue: "Grey"},
	{hex: "CFBEA5", colour: "Soft Amber", hue: "Yellow"},
	{hex: "EEDFDE", colour: "Soft Peach", hue: "Red"},
	{hex: "85494C", colour: "Solid Pink", hue: "Red"},
	{hex: "EADAC2", colour: "Solitaire", hue: "Yellow"},
	{hex: "E9ECF1", colour: "Solitude", hue: "Blue"},
	{hex: "DD6B38", colour: "Sorbus", hue: "Orange"},
	{hex: "9D7F61", colour: "Sorrell Brown", hue: "Brown"},
	{hex: "C9B59A", colour: "Sour Dough", hue: "Brown"},
	{hex: "6F634B", colour: "Soya Bean", hue: "Brown"},
	{hex: "4B433B", colour: "Space Shuttle", hue: "Brown"},
	{hex: "7B8976", colour: "Spanish Green", hue: "Green"},
	{hex: "DED1B7", colour: "Spanish White", hue: "Yellow"},
	{hex: "375D4F", colour: "Spectra", hue: "Green"},
	{hex: "6C4F3F", colour: "Spice", hue: "Brown"},
	{hex: "8B5F4D", colour: "Spicy Mix", hue: "Brown"},
	{hex: "FF1CAE", colour: "Spicy Pink", hue: "Red"},
	{hex: "B3C4D8", colour: "Spindle", hue: "Blue"},
	{hex: "F1D79E", colour: "Splash", hue: "Yellow"},
	{hex: "7ECDDD", colour: "Spray", hue: "Blue"},
	{hex: "A7FC00", colour: "Spring Bud", hue: "Green"},
	{hex: "00FF7F", colour: "Spring Green", hue: "Green"},
	{hex: "A3BD9C", colour: "Spring Rain", hue: "Green"},
	{hex: "F1F1C6", colour: "Spring Sun", hue: "Green"},
	{hex: "E9E1D9", colour: "Spring Wood", hue: "Grey"},
	{hex: "B8CA9D", colour: "Sprout", hue: "Green"},
	{hex: "A2A1AC", colour: "Spun Pearl", hue: "Blue"},
	{hex: "8F7D6B", colour: "Squirrel", hue: "Brown"},
	{hex: "325482", colour: "St Tropaz", hue: "Blue"},
	{hex: "858885", colour: "Stack", hue: "Grey"},
	{hex: "A0A197", colour: "Star Dust", hue: "Grey"},
	{hex: "D2C6B6", colour: "Stark White", hue: "Yellow"},
	{hex: "E3DD39", colour: "Starship", hue: "Green"},
	{hex: "4682B4", colour: "Steel Blue", hue: "Blue"},
	{hex: "43464B", colour: "Steel Grey", hue: "Grey"},
	{hex: "833D3E", colour: "Stiletto", hue: "Red"},
	{hex: "807661", colour: "Stonewall", hue: "Yellow"},
	{hex: "65645F", colour: "Storm Dust", hue: "Grey"},
	{hex: "747880", colour: "Storm Grey", hue: "Blue"},
	{hex: "DABE82", colour: "Straw", hue: "Yellow"},
	{hex: "946A81", colour: "Strikemaster", hue: "Violet"},
	{hex: "406356", colour: "Stromboli", hue: "Green"},
	{hex: "724AA1", colour: "Studio", hue: "Violet"},
	{hex: "8C9C9C", colour: "Submarine", hue: "Blue"},
	{hex: "EEEFDF", colour: "Sugar Cane", hue: "Green"},
	{hex: "C6EA80", colour: "Sulu", hue: "Green"},
	{hex: "8FB69C", colour: "Summer Green", hue: "Green"},
	{hex: "38B0DE", colour: "Summer Sky", hue: "Blue"},
	{hex: "EF8E38", colour: "Sun", hue: "Orange"},
	{hex: "C4AA4D", colour: "Sundance", hue: "Yellow"},
	{hex: "F8AFA9", colour: "Sundown", hue: "Red"},
	{hex: "DAC01A", colour: "Sunflower", hue: "Yellow"},
	{hex: "C76155", colour: "Sunglo", hue: "Red"},
	{hex: "FFCC33", colour: "Sunglow", hue: "Orange"},
	{hex: "C0514A", colour: "Sunset", hue: "Red"},
	{hex: "FE4C40", colour: "Sunset Orange", hue: "Orange"},
	{hex: "FA9D49", colour: "Sunshade", hue: "Orange"},
	{hex: "FFB437", colour: "Supernova", hue: "Yellow"},
	{hex: "B8D4BB", colour: "Surf", hue: "Green"},
	{hex: "C3D6BD", colour: "Surf Crest", hue: "Green"},
	{hex: "007B77", colour: "Surfie Green", hue: "Green"},
	{hex: "7C9F2F", colour: "Sushi", hue: "Green"},
	{hex: "8B8685", colour: "Suva Grey", hue: "Grey"},
	{hex: "252F2F", colour: "Swamp", hue: "Green"},
	{hex: "DAE6DD", colour: "Swans Down", hue: "Grey"},
	{hex: "F9E176", colour: "Sweet Corn", hue: "Yellow"},
	{hex: "EE918D", colour: "Sweet Pink", hue: "Red"},
	{hex: "D7CEC5", colour: "Swirl", hue: "Grey"},
	{hex: "DBD0CA", colour: "Swiss Coffee", hue: "Grey"},
	{hex: "F6AE78", colour: "Tacao", hue: "Orange"},
	{hex: "D2B960", colour: "Tacha", hue: "Yellow"},
	{hex: "DC722A", colour: "Tahiti Gold", hue: "Orange"},
	{hex: "D8CC9B", colour: "Tahuna Sands", hue: "Yellow"},
	{hex: "853534", colour: "Tall Poppy", hue: "Red"},
	{hex: "A39977", colour: "Tallow", hue: "Yellow"},
	{hex: "752B2F", colour: "Tamarillo", hue: "Red"},
	{hex: "D2B48C", colour: "Tan", hue: "Brown"},
	{hex: "B8B5A1", colour: "Tana", hue: "Green"},
	{hex: "1E2F3C", colour: "Tangaroa", hue: "Blue"},
	{hex: "F28500", colour: "Tangerine", hue: "Orange"},
	{hex: "FFCC00", colour: "Tangerine Yellow", hue: "Yellow"},
	{hex: "D46F31", colour: "Tango", hue: "Orange"},
	{hex: "7C7C72", colour: "Tapa", hue: "Green"},
	{hex: "B37084", colour: "Tapestry", hue: "Red"},
	{hex: "DEF1DD", colour: "Tara", hue: "Green"},
	{hex: "253C48", colour: "Tarawera", hue: "Blue"},
	{hex: "BAC0B3", colour: "Tasman", hue: "Grey"},
	{hex: "483C32", colour: "Taupe", hue: "Grey"},
	{hex: "8B8589", colour: "Taupe Grey", hue: "Grey"},
	{hex: "643A48", colour: "Tawny Port", hue: "Red"},
	{hex: "496569", colour: "Tax Break", hue: "Blue"},
	{hex: "2B4B40", colour: "Te Papa Green", hue: "Green"},
	{hex: "BFB5A2", colour: "Tea", hue: "Yellow"},
	{hex: "D0F0C0", colour: "Tea Green", hue: "Green"},
	{hex: "F883C2", colour: "Tea Rose", hue: "Orange"},
	{hex: "AB8953", colour: "Teak", hue: "Yellow"},
	{hex: "008080", colour: "Teal", hue: "Blue"},
	{hex: "254855", colour: "Teal Blue", hue: "Blue"},
	{hex: "3C2126", colour: "Temptress", hue: "Brown"},
	{hex: "CD5700", colour: "Tenne (Tawny)", hue: "Orange"},
	{hex: "F4D0A4", colour: "Tequila", hue: "Yellow"},
	{hex: "E2725B", colour: "Terra Cotta", hue: "Red"},
	{hex: "ECE67E", colour: "Texas", hue: "Green"},
	{hex: "FCB057", colour: "Texas Rose", hue: "Orange"},
	{hex: "B1948F", colour: "Thatch", hue: "Brown"},
	{hex: "544E31", colour: "Thatch Green", hue: "Yellow"},
	{hex: "D8BFD8", colour: "Thistle", hue: "Violet"},
	{hex: "4D4D4B", colour: "Thunder", hue: "Grey"},
	{hex: "923830", colour: "Thunderbird", hue: "Red"},
	{hex: "97422D", colour: "Tia Maria", hue: "Orange"},
	{hex: "B9C3BE", colour: "Tiara", hue: "Grey"},
	{hex: "184343", colour: "Tiber", hue: "Green"},
	{hex: "FC80A5", colour: "Tickle Me Pink", hue: "Red"},
	{hex: "F0F590", colour: "Tidal", hue: "Green"},
	{hex: "BEB4AB", colour: "Tide", hue: "Brown"},
	{hex: "324336", colour: "Timber Green", hue: "Green"},
	{hex: "D9D6CF", colour: "Timberwolf", hue: "Grey"},
	{hex: "DDD6E1", colour: "Titan White", hue: "Violet"},
	{hex: "9F715F", colour: "Toast", hue: "Brown"},
	{hex: "6D5843", colour: "Tobacco Brown", hue: "Brown"},
	{hex: "44362D", colour: "Tobago", hue: "Brown"},
	{hex: "3E2631", colour: "Toledo", hue: "Violet"},
	{hex: "2D2541", colour: "Tolopea", hue: "Violet"},
	{hex: "4F6348", colour: "Tom Thumb", hue: "Green"},
	{hex: "FF6347", colour: "Tomato", hue: "Red"},
	{hex: "E79E88", colour: "Tonys Pink", hue: "Orange"},
	{hex: "817C87", colour: "Topaz", hue: "Violet"},
	{hex: "FD0E35", colour: "Torch Red", hue: "Red"},
	{hex: "353D75", colour: "Torea Bay", hue: "Blue"},
	{hex: "374E88", colour: "Tory Blue", hue: "Blue"},
	{hex: "744042", colour: "Tosca", hue: "Red"},
	{hex: "9CACA5", colour: "Tower Grey", hue: "Green"},
	{hex: "6DAFA7", colour: "Tradewind", hue: "Green"},
	{hex: "DDEDE9", colour: "Tranquil", hue: "Blue"},
	{hex: "E2DDC7", colour: "Travertine", hue: "Green"},
	{hex: "E2813B", colour: "Tree Poppy", hue: "Orange"},
	{hex: "7E8424", colour: "Trendy Green", hue: "Green"},
	{hex: "805D80", colour: "Trendy Pink", hue: "Violet"},
	{hex: "C54F33", colour: "Trinidad", hue: "Orange"},
	{hex: "AEC9EB", colour: "Tropical Blue", hue: "Blue"},
	{hex: "00755E", colour: "Tropical Rain Forest", hue: "Green"},
	{hex: "4C5356", colour: "Trout", hue: "Grey"},
	{hex: "8E72C7", colour: "True V", hue: "Violet"},
	{hex: "454642", colour: "Tuatara", hue: "Grey"},
	{hex: "F9D3BE", colour: "Tuft Bush", hue: "Orange"},
	{hex: "E3AC3D", colour: "Tulip Tree", hue: "Yellow"},
	{hex: "DEA681", colour: "Tumbleweed", hue: "Brown"},
	{hex: "46494E", colour: "Tuna", hue: "Grey"},
	{hex: "585452", colour: "Tundora", hue: "Grey"},
	{hex: "F5CC23", colour: "Turbo", hue: "Yellow"},
	{hex: "A56E75", colour: "Turkish Rose", hue: "Red"},
	{hex: "AE9041", colour: "Turmeric", hue: "Yellow"},
	{hex: "40E0D0", colour: "Turquoise", hue: "Blue"},
	{hex: "6CDAE7", colour: "Turquoise Blue", hue: "Blue"},
	{hex: "363E1D", colour: "Turtle Green", hue: "Green"},
	{hex: "AD6242", colour: "Tuscany", hue: "Orange"},
	{hex: "E3E5B1", colour: "Tusk", hue: "Green"},
	{hex: "BF914B", colour: "Tussock", hue: "Yellow"},
	{hex: "F8E4E3", colour: "Tutu", hue: "Red"},
	{hex: "DAC0CD", colour: "Twilight", hue: "Violet"},
	{hex: "F4F6EC", colour: "Twilight Blue", hue: "Grey"},
	{hex: "C19156", colour: "Twine", hue: "Yellow"},
	{hex: "66023C", colour: "Tyrian Purple", hue: "Violet"},
	{hex: "FF6FFF", colour: "Ultra Pink", hue: "Red"},
	{hex: "120A8F", colour: "Ultramarine", hue: "Blue"},
	{hex: "D4574E", colour: "Valencia", hue: "Red"},
	{hex: "382C38", colour: "Valentino", hue: "Violet"},
	{hex: "2A2B41", colour: "Valhalla", hue: "Violet"},
	{hex: "523936", colour: "Van Cleef", hue: "Brown"},
	{hex: "CCB69B", colour: "Vanilla", hue: "Brown"},
	{hex: "EBD2D1", colour: "Vanilla Ice", hue: "Red"},
	{hex: "FDEFD3", colour: "Varden", hue: "Yellow"},
	{hex: "C80815", colour: "Venetian Red", hue: "Red"},
	{hex: "2C5778", colour: "Venice Blue", hue: "Blue"},
	{hex: "8B7D82", colour: "Venus", hue: "Violet"},
	{hex: "62603E", colour: "Verdigris", hue: "Grey"},
	{hex: "48531A", colour: "Verdun Green", hue: "Green"},
	{hex: "FF4D00", colour: "Vermilion", hue: "Red"},
	{hex: "5C4033", colour: "Very Dark Brown", hue: "Brown"},
	{hex: "CDCDCD", colour: "Very Light Grey", hue: "Grey"},
	{hex: "A85533", colour: "Vesuvius", hue: "Orange"},
	{hex: "564985", colour: "Victoria", hue: "Violet"},
	{hex: "5F9228", colour: "Vida Loca", hue: "Green"},
	{hex: "4DB1C8", colour: "Viking", hue: "Blue"},
	{hex: "955264", colour: "Vin Rouge", hue: "Red"},
	{hex: "C58F9D", colour: "Viola", hue: "Red"},
	{hex: "2E2249", colour: "Violent Violet", hue: "Violet"},
	{hex: "EE82EE", colour: "Violet", hue: "Violet"},
	{hex: "9F5F9F", colour: "Violet Blue", hue: "Violet"},
	{hex: "F7468A", colour: "Violet Red", hue: "Red"},
	{hex: "40826D", colour: "Viridian", hue: "Blue"},
	{hex: "4B5F56", colour: "Viridian Green", hue: "Green"},
	{hex: "F9E496", colour: "Vis Vis", hue: "Yellow"},
	{hex: "97D5B3", colour: "Vista Blue", hue: "Green"},
	{hex: "E3DFD9", colour: "Vista White", hue: "Grey"},
	{hex: "FF9980", colour: "Vivid Tangerine", hue: "Orange"},
	{hex: "803790", colour: "Vivid Violet", hue: "Violet"},
	{hex: "4E2728", colour: "Volcano", hue: "Red"},
	{hex: "443240", colour: "Voodoo", hue: "Violet"},
	{hex: "36383C", colour: "Vulcan", hue: "Grey"},
	{hex: "D4BBB1", colour: "Wafer", hue: "Orange"},
	{hex: "5B6E91", colour: "Waikawa Grey", hue: "Blue"},
	{hex: "4C4E31", colour: "Waiouru", hue: "Green"},
	{hex: "E4E2DC", colour: "Wan White", hue: "Grey"},
	{hex: "849137", colour: "Wasabi", hue: "Green"},
	{hex: "B6ECDE", colour: "Water Leaf", hue: "Green"},
	{hex: "006E4E", colour: "Watercourse", hue: "Green"},
	{hex: "D6CA3D", colour: "Wattle", hue: "Green"},
	{hex: "F2CDBB", colour: "Watusi", hue: "Orange"},
	{hex: "EEB39E", colour: "Wax Flower", hue: "Orange"},
	{hex: "FDD7D8", colour: "We Peep", hue: "Red"},
	{hex: "4C6B88", colour: "Wedgewood", hue: "Blue"},
	{hex: "8E3537", colour: "Well Read", hue: "Red"},
	{hex: "5C512F", colour: "West Coast", hue: "Yellow"},
	{hex: "E5823A", colour: "West Side", hue: "Orange"},
	{hex: "D4CFC5", colour: "Westar", hue: "Grey"},
	{hex: "F1919A", colour: "Wewak", hue: "Red"},
	{hex: "F5DEB3", colour: "Wheat", hue: "Brown"},
	{hex: "DFD7BD", colour: "Wheatfield", hue: "Yellow"},
	{hex: "D29062", colour: "Whiskey", hue: "Orange"},
	{hex: "D4915D", colour: "Whiskey Sour", hue: "Orange"},
	{hex: "EFE6E6", colour: "Whisper", hue: "Grey"},
	{hex: "FFFFFF", colour: "White", hue: "White"},
	{hex: "D7EEE4", colour: "White Ice", hue: "Green"},
	{hex: "E7E5E8", colour: "White Lilac", hue: "Blue"},
	{hex: "EEE7DC", colour: "White Linen", hue: "Grey"},
	{hex: "F8F6D8", colour: "White Nectar", hue: "Green"},
	{hex: "DAD6CC", colour: "White Pointer", hue: "Grey"},
	{hex: "D4CFB4", colour: "White Rock", hue: "Green"},
	{hex: "F5F5F5", colour: "White Smoke", hue: "White"},
	{hex: "7A89B8", colour: "Wild Blue Yonder", hue: "Blue"},
	{hex: "E3D474", colour: "Wild Rice", hue: "Green"},
	{hex: "E7E4DE", colour: "Wild Sand", hue: "Grey"},
	{hex: "FF3399", colour: "Wild Strawberry", hue: "Red"},
	{hex: "FD5B78", colour: "Wild Watermelon", hue: "Red"},
	{hex: "BECA60", colour: "Wild Willow", hue: "Green"},
	{hex: "53736F", colour: "William", hue: "Green"},
	{hex: "DFE6CF", colour: "Willow Brook", hue: "Green"},
	{hex: "69755C", colour: "Willow Grove", hue: "Green"},
	{hex: "462C77", colour: "Windsor", hue: "Violet"},
	{hex: "522C35", colour: "Wine Berry", hue: "Red"},
	{hex: "D0C383", colour: "Winter Hazel", hue: "Yellow"},
	{hex: "F9E8E2", colour: "Wisp Pink", hue: "Red"},
	{hex: "C9A0DC", colour: "Wisteria", hue: "Violet"},
	{hex: "A29ECD", colour: "Wistful", hue: "Blue"},
	{hex: "FBF073", colour: "Witch Haze", hue: "Green"},
	{hex: "302621", colour: "Wood Bark", hue: "Brown"},
	{hex: "463629", colour: "Woodburn", hue: "Brown"},
	{hex: "626746", colour: "Woodland", hue: "Green"},
	{hex: "45402B", colour: "Woodrush", hue: "Yellow"},
	{hex: "2B3230", colour: "Woodsmoke", hue: "Grey"},
	{hex: "554545", colour: "Woody Brown", hue: "Brown"},
	{hex: "75876E", colour: "Xanadu", hue: "Green"},
	{hex: "FFFF00", colour: "Yellow", hue: "Yellow"},
	{hex: "9ACD32", colour: "Yellow Green", hue: "Green"},
	{hex: "73633E", colour: "Yellow Metal", hue: "Yellow"},
	{hex: "FFAE42", colour: "Yellow Orange", hue: "Orange"},
	{hex: "F49F35", colour: "Yellow Sea", hue: "Yellow"},
	{hex: "FFC5BB", colour: "Your Pink", hue: "Red"},
	{hex: "826A21", colour: "Yukon Gold", hue: "Yellow"},
	{hex: "C7B882", colour: "Yuma", hue: "Yellow"},
	{hex: "6B5A5A", colour: "Zambezi", hue: "Brown"},
	{hex: "B2C6B1", colour: "Zanah", hue: "Green"},
	{hex: "C6723B", colour: "Zest", hue: "Orange"},
	{hex: "3B3C38", colour: "Zeus", hue: "Grey"},
	{hex: "81A6AA", colour: "Ziggurat", hue: "Blue"},
	{hex: "EBC2AF", colour: "Zinnwaldite", hue: "Brown"},
	{hex: "DEE3E3", colour: "Zircon", hue: "Grey"},
	{hex: "DDC283", colour: "Zombie", hue: "Yellow"},
	{hex: "A29589", colour: "Zorba", hue: "Brown"},
	{hex: "17462E", colour: "Zuccini", hue: "Green"},
	{hex: "CDD5D5", colour: "Zumthor", hue: "Grey"},
}
